### ISSUE TITLE
Panic button

### ISSUE THREAD

**Issue by 1K26** [Linesmerrill/police-cad#100]
Hi i love your website but i feel like a panic button would be nice and mabe a 10-08 10-07 10-06 10-23 10-80 ect and a dispatch mode if you know what i mean thanks

**Comment by AndrewMichael5736** [comment]
I’d feel this would bring a whole new aspect to rp’s. I’d vote for this!

**Comment by Linesmerrill** [comment]
@1K26 100% agree with you on this! We are working on a new dispatch website that would handle all of this and more. Let me mark this appropriately. Thanks for the suggestion!

**Comment by Linesmerrill** [comment]
Just had another request for this from Carsontube.

**Comment by Linesmerrill** [comment]
Additional request: https://github.com/Linesmerrill/police-cad/issues/184

**Comment by Linesmerrill** [comment]
Will be completed here: https://github.com/Linesmerrill/police-cad/pull/207
