### ISSUE TITLE
Bug On Lines police cad

### ISSUE THREAD

**Issue by LieutenantCook** [Linesmerrill/police-cad#103]
**Desktop (please complete the following information):**
 - OS: [e.g. Lenvo]
 - Browser [e.g. chrome,]
 - Version [e.g.300e ]

**Additional context**
When putting in the name and the DOB for the arrest report and the citation and warning reports, once clicking the blue search button it dosent come back to anything, i did a little test and make a new persona with the civillians and loo its info up as a cop and nothing came up. please fix this. my server cant write reports anymore now have a good day and goodbye

**Comment by Linesmerrill** [comment]
Thank you for bringing this to our attention, we are looking into this now.

**Comment by Linesmerrill** [comment]
# Test 1

### Creating a New Civilian:

![image](https://user-images.githubusercontent.com/15384983/73409867-c0da3700-42bd-11ea-9d9b-25fb238fca99.png)

### Shows up on Civilian Dashboard:

![image](https://user-images.githubusercontent.com/15384983/73409896-d4859d80-42bd-11ea-8f88-1aedc304db4a.png)

### Searching in the Person Database on the Police Dashboard

![image](https://user-images.githubusercontent.com/15384983/73409941-fa12a700-42bd-11ea-9d97-5fb7f2ffbbfd.png)

### Results from person search:

![image](https://user-images.githubusercontent.com/15384983/73409960-072f9600-42be-11ea-8727-84dd2cc3359e.png)

### Issuing a Citation

![image](https://user-images.githubusercontent.com/15384983/73409987-1c0c2980-42be-11ea-86b5-759d51fb0bea.png)

### Searching for User by entering information and pressing search button:

![image](https://user-images.githubusercontent.com/15384983/73410019-380fcb00-42be-11ea-9941-90d739a25781.png)

### Selecting result from table and it should autofill the 'Selected ID' input:

![image](https://user-images.githubusercontent.com/15384983/73410039-4fe74f00-42be-11ea-9232-323bbe6aaf15.png)

### Submit Citation and search in Name Database and it shows the new citation:

![image](https://user-images.githubusercontent.com/15384983/73410101-7c9b6680-42be-11ea-9635-7d5e0314abcd.png)


Please follow these steps and if you still encounter issues please let us know and provide detailed steps like ours to make sure we can debug your issues quickly. 😄

**Comment by Linesmerrill** [comment]
Thank you for submitting this bug. We found the issue and it was related to a case sensitive search for names. So 'james conner' would not return any results but 'James Conner' would. We have fixed this and it has been released: https://github.com/Linesmerrill/police-cad/releases/tag/v0.9.3
