### ISSUE TITLE
Warrants rework

### ISSUE THREAD

**Issue by CoffeeLight535** [Linesmerrill/police-cad#107]
**Describe the solution you'd like**
A way for officers to remove warrants and for citizens to be able to add warrant reason

**Implementation Details**
Add a drop down list of warrant reasons when selecting if you want to have warrants or not. With things like, Failure to appear, Murder, Felony Evasion, Prison Escape, and other where the civilian can write what they want the warrant reason to be. In the police cad when there name is searched up it will say the person has a warrant for (reason, ex. Failure to appear in court ).

If the drop down list doesn’t work then another page on the civ cad called create warrants can be placed where you select the person name ( like on the vehicle registration page ) and the warrant reason with a list of all the reason like explained above and the other option in witch they can put what they want.

**Possible Side Effects**
Not really a coder so to my knowledge there is none

**Comment by Linesmerrill** [comment]
Amazing suggestion! Our team loved it as well. We released this addition here: https://github.com/Linesmerrill/police-cad/releases/tag/v0.9.6

🥇Thank you @CoffeeLight535 for the suggestion!
