### ISSUE TITLE
Twotter

### ISSUE THREAD

**Issue by keedanthegodgamer** [Linesmerrill/police-cad#110]
I would like to have it so the civs can go on there phone and go to twotter and all of that. I would love to help in the make of it if you would like me to. The only thing I have in a computer phorm would be Chromebook. Let me know

**Comment by Linesmerrill** [comment]
@keedanthegodgamer thanks for the suggestion. Would this be in the website or in the GTAV game?

**Comment by keedanthegodgamer** [comment]
Game

**Comment by Linesmerrill** [comment]
Ok thank you for clarifying. For right now we are not planning on building this sort of integration. So ill go ahead and close this and tag appropriately. It will remain as a closed issue if we do ever get around to building this integration.
