### ISSUE TITLE
Truckers

### ISSUE THREAD

**Issue by S8X-Rocket** [Linesmerrill/police-cad#111]
So on there you can add your deliveries and make an estimated time. Put an adress in and the delviries credentials in. Name of the truck driver and make it so when you get there it says delivered. Or when you about to depart you can depart on the journey

**Comment by Linesmerrill** [comment]
Hi @S8X-Rocket thanks for the suggestion! Yeah I love this idea. Im not 100% sure how we would implement this right now, but I will discuss with our team and get this prioritized. Awesome.
