### ISSUE TITLE
Custom Citation/Warning Entries

### ISSUE THREAD

**Issue by Jmish08** [Linesmerrill/police-cad#112]
**Describe the solution you'd like**
The preset charges/citations are ok. They could be improved upon themselves but the most versatile option would be to allow users to enter custom charges again. 

**Implementation Details**

**Possible Side Effects**
Users may enter inappropriate things into the text boxes, to counter this have blacklisted terms that are not allowed.

**Comment by Linesmerrill** [comment]
Love it! Our team just pushed out an update with this added functionality. For more info you can check out release notes here: https://github.com/Linesmerrill/police-cad/releases/tag/v0.9.5

🏅 Thanks for the suggestion! 😄
