### ISSUE TITLE
Lines Police CAD

### ISSUE THREAD

**Issue by cartherton** [Linesmerrill/police-cad#116]
**Describe the solution you'd like**
I would just like to also have the ability to place a BOLO on a car or a person.

**Comment by Linesmerrill** [comment]
Hi @cartherton this is a great suggestion! We actually already have this feature planned to be release with the new dispatch website. We are actively working on this but this will be an option once we finish development and testing it. Feel free to follow along with the work here: https://github.com/Linesmerrill/police-cad/issues/104
