### ISSUE TITLE
Fire/EMS Scene Report Feature

### ISSUE THREAD

**Issue by firefightermorrow** [Linesmerrill/police-cad#117]
Hello Dev's of Lines Police CAD, i would like to suggest a new feature for the Fire Dept portion of the CAD. It would add to the CAD if you could work on implanting a death/scene report feature. This would allow Fire personal to pronounce a civilian dead, or to give a report on the injuries a civilian withstands. This feature would add to the already amazing CAD that you have, as well as help to make the rp more realistic.

I appreciate you spending the time to take my thoughts into consideration

**Comment by Linesmerrill** [comment]
Hi @firefightermorrow thanks for the suggestion! Yeah I really like this idea. We will get this prioritized in our backlog. Thank you.
