### ISSUE TITLE
Lines Police Cad Suggestion for dispatch

### ISSUE THREAD

**Issue by mrthegamer1** [Linesmerrill/police-cad#119]
dispatch group

**Implementation Details**
Basically kind of like the cop group but instead a dispatch so if they are unable to use cad a dispatcher can  do the name plate warrants arrest report ETC.

**Possible Side Effects**
None that i can think of 
![Screenshot_2020-02-18 Lines Police - CAD](https://user-images.githubusercontent.com/57550611/74788922-bab1f780-5278-11ea-9011-c60d065ed07d.png)

**Comment by Linesmerrill** [comment]
@mrthegamer1 Awesome suggestion! This is something we are actually already working on right now as we build out the new community website. Stay tuned for more updates and check out the other feature we have to track this work here: https://github.com/Linesmerrill/police-cad/issues/104
