### ISSUE TITLE
More parts to the Fire/EMS Side

### ISSUE THREAD

**Issue by OfficerLosSantos** [Linesmerrill/police-cad#120]
**Describe the solution you'd like**
(_A clear and concise description of what you want to happen._)

I would like more things to do on the fire and ems side of the lines police cad also a dispatch side

**Implementation Details**
(_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_)

you would add medical background checks and current calls as well as the dispatch side which would have you make a call the location and units responding

**Possible Side Effects**
(_What are some of the adverse reactions that adding this could bring to the website?_)

more roleplayers would come to the cad and use it

**Comment by Linesmerrill** [comment]
Hi @OfficerLosSantos thanks for adding this suggestion! Looks like there are two parts to this suggestion:

1. Add additional options for Fire/EMS when they are logged into the website. 
2. Add a dispatch side which would include the call location and units responding.

Lets keep this ticket for number 1. For number 2 we will include this in our dispatch ticket which we already have.

Awesome 👏

**Comment by OfficerLosSantos** [comment]
Hey @Linesmerrill sorry I didn't get back to you I was dealing with some game stuff for the game I am developing. That sounds good to me is there anything you would like me to do to help in this process

**Comment by Linesmerrill** [comment]
No worries, just trying to clean up any of the really old stuff from our backlog. We will get this prioritized. Thank you!

**Comment by OfficerLosSantos** [comment]
No problem

**Comment by Linesmerrill** [comment]
WIll be completed here: https://github.com/Linesmerrill/police-cad/pull/231
