### ISSUE TITLE
HOW TO PURCHASE 

### ISSUE THREAD

**Issue by austinator2018** [Linesmerrill/police-cad#121]
HELLO HOW DO I PURCHASE A CAD ( COMMUNITY AID DISPATCH)

**Comment by Linesmerrill** [comment]
Hi @austinator2018 Thanks for adding this question. Currently right now it is 100% free to use. As we build out more individual dashboards that specific communities can use, we may introduce a payment option. This is still being developed and worked on so for right now there is no way to purchase a CAD.
