### ISSUE TITLE
Map of GTAV with Postal Codes

### ISSUE THREAD

**Issue by jefferey426** [Linesmerrill/police-cad#122]
**Describe the solution you'd like** i would like a map of gta5 with postal codes for the police and civs and fire 
A option like the 10 codes but it should say map and you have postal codes on it for gta 5
**Implementation Details** none
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?
It would make it great for people on console so they have postal codes to dispatch cops to if your a cop or ems make it more realistic

**Comment by Linesmerrill** [comment]
@jefferey426 Thanks for the suggestion. Do you happen to have a map of GTAV with the postal codes that we could use for our website?
