### ISSUE TITLE
New features for plate check

### ISSUE THREAD

**Issue by OrbitalEnd48401** [Linesmerrill/police-cad#123]
**Describe the solution you'd like**
I live in the U.K. and the police over here have additional notes when conducting a licence plate check.

**Implementation Details**
I was wondering if you could add a Make box which will contain the make of the vehicle, a box for “makers” where cops can add notes, for example if the bike was used in a robbery or has been causing a nuisance then the cops can add that. So when the cops pull the bike over and do a plate check, they can see the markers that the bike has been used in a robbery or has false plates etc.

**Possible Side Effects**
It saves hassle and the cops don’t forget about a particular case, so if a bike was used in a robbery the other cop will know immediately upon checking the plate.

Adding make onto the vehicle makes it more realistic.

**Comment by Linesmerrill** [comment]
Awesome suggestion! We will get this prioritized and put in our backlog. Thank you @OrbitalEnd48401!

**Comment by OrbitalEnd48401** [comment]
Ha thanks bud, I’m on your discoed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
