### ISSUE TITLE
we need to  right  verbal warning and right tickets. thank you  

### ISSUE THREAD

**Issue by trooper3454** [Linesmerrill/police-cad#127]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Hi @trooper3454 ! We do currently support writing warnings and tickets.

# How to issue a warning/citation

- Simply make sure you are logged in as a police officer
- Look up a civilian by Name
- You should see something like this:
![image](https://user-images.githubusercontent.com/15384983/77229751-c8df8600-6b4c-11ea-9152-052c8f9f2166.png)

- Then click on 'Issue Citation' if you want to write a ticket, or 'Issue Warning' if you want to give them a written warning.

If you have any issue with this just let us know. Thanks

**Comment by trooper3454** [comment]
thanks we needed this what the next update
