### ISSUE TITLE
Add ticket details when clicking on tickets

### ISSUE THREAD

**Issue by corbinlarchr** [Linesmerrill/police-cad#128]
**Describe the solution you'd like**
can we make i where we can have the tictets be able to be viewed so we canget details of why ticket was issued

**Implementation Details**
N/A

**Possible Side Effects**
N/A

**Comment by Linesmerrill** [comment]
Yeah this is a great suggestion @corbinlarchr ! Good news is that we already have this feature request in our backlog, so be sure to follow along with that progress here: https://github.com/Linesmerrill/police-cad/issues/79
