### ISSUE TITLE
When i go to search a plate number i type it in and then when i press search it kicks me out of my account and then it will just have me log back in but it does the same thing.

### ISSUE THREAD

**Issue by kobe617** [Linesmerrill/police-cad#130]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Linesmerrill** [comment]
Thank you for bringing this to our attention. We were load testing some scaling with our application and found issues with the Login, Name and Plate search. We have a fix in right now that should prevent this from happening. But we will continue to make the website a bit more resilient over the next 24-48 hours.
