### ISSUE TITLE
Plate: R.O. D.O.B.

### ISSUE THREAD

**Issue by Jmish08** [Linesmerrill/police-cad#132]
**Describe the solution you'd like**
When running a license plate, the system should give the date of birth of the registered owner. 

**Implementation Details**
No specific details.

**Possible Side Effects**
It is possible some people may feel this is unnecessary or unrealistic, however, - at least in my county - you get the date of birth when you run a plate, you actually get all relevant information from the persons database.

**Comment by Linesmerrill** [comment]
Awesome suggestion! @Jmish08 I will toss this in our backlog 😄

**Comment by Linesmerrill** [comment]
Looks like we already have this in our backlog here: https://github.com/Linesmerrill/police-cad/issues/109. Follow along with the progress using this link.
