### ISSUE TITLE
Penal Codes

### ISSUE THREAD

**Issue by UncleCohen** [Linesmerrill/police-cad#133]
I think it would be a good idea to have penal codes in the police section of the CAD. It would be extremely helpful for people (like me) who struggle with penal codes. With it, we can see if someone has broken any laws, and what laws have been broken. It would be an awesome addition to Lines Police CAD!

**Comment by Linesmerrill** [comment]
Love it @UncleCohen ! Do you happen to have a list of penal codes we could use on our website? Make sure we have permission to use any that you supply us as well. Once we have the penal codes we can for sure get those added to the website. Thanks

**Comment by UncleCohen** [comment]
@Linesmerrill I can take a look

**Comment by UncleCohen** [comment]
@Linesmerrill Question: Where did you get the 10 codes from, and could thatcsource possibly have a penal sheet?

**Comment by Linesmerrill** [comment]
@UncleCohen We had most of those donated by a member of our community. Let me do some research and see if I can find a generic penal code sheet. 👍

**Comment by UncleCohen** [comment]
@Linesmerrill Ok
