### ISSUE TITLE
[Community Update] Leaving Communities 

### ISSUE THREAD

**Issue by Jmish08** [Linesmerrill/police-cad#137]
**Describe the solution you'd like**
There is currently no way to leave a community and go back to the general database. There should be a button that allows you to completely leave the community you are in and search the general database. (For this I am considering the 'general database' as the database before communities were implemented. )

**Implementation Details**
IMPORTANT: The general database should not include data from community-specific databases and vice versa (this should include citations, registered vehicles, names, etc.). 

 Communities and the General Database should be completely separate. 

**Possible Side Effects**
No Specific Details.

**Comment by Linesmerrill** [comment]
Thank you @Jmish08 ! We are working on testing this right now before it will be released.

**Comment by Linesmerrill** [comment]
Similar to: https://github.com/Linesmerrill/police-cad/issues/135. But this ticket has more details that should be followed.

**Comment by Linesmerrill** [comment]
Will be fixed here: https://github.com/Linesmerrill/police-cad/pull/138

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/releases/tag/v1.0.1
