### ISSUE TITLE
Name Search System

### ISSUE THREAD

**Issue by Adam8081** [Linesmerrill/police-cad#140]
A good idea for improving the name search is to remove the "Date of Birth" option or improve on it. I find it difficult whenever searching someones name and it's hard to type their birthdate in because people have different variations like "11/14/1996" or "11/14/96" or even "11141996". You can't find the person's record without having the birthdate. I request to have the "Date of Birth" option removed OR having the Date of Birth option as a preset format so that the format is fixed and cannot be changed to a random format, such as selecting the number of their month, date and year rather than typing it and it would be easier. So it's only format would be like "11/14/96" and that's all.

**Comment by Linesmerrill** [comment]
@Adam8081 thank you for the suggestion! If you join a community then we have taken this search field completely away. But for the generic search we found that it is nearly impossible to sort though 100 "John Smith's", plus the load it was putting on the server was also not optimal. By adding a simple DOB search field we were able to increase performance and also reduce the number of records returned when searching a name. 

Our take away from your suggestion will be to try and make the DOB search easier to use, like you mentioned. Ill toss this into our backlog and have the team take a look. Thank you!
