### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by TrueTexan** [Linesmerrill/police-cad#141]
Add a Dispatcher and a panic button for the police and fire so that they can get dispatch the units and add more to the police and a phone to civs

**Comment by Linesmerrill** [comment]
💯 agree @TrueTexan . We already have a request for this and you can track the work here: https://github.com/Linesmerrill/police-cad/issues/104

**Comment by TrueTexan** [comment]
Ok thx for the information.

Sent from my iPad

On Mar 30, 2020, at 9:02 PM, Merrill Lines <notifications@github.com> wrote:

﻿

💯 agree @TrueTexan<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTrueTexan&data=02%7C01%7C%7C9d0d50165cb241f6eea008d7d5178da4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637212169437578525&sdata=%2B7y9XHKTJa7DuqfY0c3dcRDPAFkVxIe9ADKDaabJf%2Fs%3D&reserved=0> . We already have a request for this and you can track the work here: #104<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLinesmerrill%2Fpolice-cad%2Fissues%2F104&data=02%7C01%7C%7C9d0d50165cb241f6eea008d7d5178da4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637212169437578525&sdata=Jz%2FXGn5WXIr7muM2MLsf8MGFYayhEEqQ0Qf7kxc%2BmE8%3D&reserved=0>
