### ISSUE TITLE
Fire and Ems closing/ fire and ems is not working it brings you to an error loading screen. I tried refreshing then a reset of the device and both arent working.

### ISSUE THREAD

**Issue by officerhowreya** [Linesmerrill/police-cad#142]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Linesmerrill** [comment]
Yes thank you @officerhowreya for putting a bug in here for us. We have identified the issue and deployed a hotfix to the website. For more information please see the work associated to this: https://github.com/Linesmerrill/police-cad/pull/143.
