### ISSUE TITLE
when we create a person there should be a bar where we can put any type of job

### ISSUE THREAD

**Issue by MauriceS410** [Linesmerrill/police-cad#146]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Hi @MauriceS410 thanks for this suggestion. We do already have an input for Occupation. This is where you should specify the job for that person you are creating. 

![image](https://user-images.githubusercontent.com/15384983/78458371-9746de80-7665-11ea-9f5c-78ca4711be89.png)

If you need to modify the occupation, you can always click on the civilian and modify any of the details listed for that civilian. 👍
