### ISSUE TITLE
dispatch/officers/ems/fire possibly civs

### ISSUE THREAD

**Issue by MauriceS410** [Linesmerrill/police-cad#148]
adding active calls tab and on duty with emergency servicemen/women names on one call
 in a community. can see others emergency servicemen/women/"dispatch" notes to relate on. maybe could have feature for the permissions

**Comment by Linesmerrill** [comment]
Awesome suggestion! let me add these details to our Dispatch feature which is already in development. You can track that here: https://github.com/Linesmerrill/police-cad/issues/104
