### ISSUE TITLE
Active Call log for Dispatch 

### ISSUE THREAD

**Issue by PankakeLord14** [Linesmerrill/police-cad#157]
**Describe the solution you'd like**
 I would like to see an active call log so that we can see what calls emergency services have gotten.

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for an input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)
 Possibly adding a Dispatch role to the main screen.

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?
I am not certain about any side effects this could bring to the website.

**Comment by Linesmerrill** [comment]
Additional details for https://github.com/Linesmerrill/police-cad/issues/30
