### ISSUE TITLE
Make calls with CAD

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#163]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Make a radio for the police and a CAD to see calls and the radio with cool sound effects!!

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
[radio_clics_sound_bytes.zip](https://github.com/Linesmerrill/police-cad/files/4497090/radio_clics_sound_bytes.zip)

**Comment by Brooklyn-8** [comment]
This would be very to have in the cad. Many other cads have a radio that I have used before and it was very nice to use instead of discord or as an example: Game chat or PS$ party chat.
