### ISSUE TITLE
Add Medical Reports for Civilians/EMS

### ISSUE THREAD

**Issue by NibbaHub** [Linesmerrill/police-cad#176]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- can you make a 911 upgrade for civilians so that a civilian can report to the emergency center? The report could appear to the police, the fire department and paramedics!
Best regards Los-Santos state rp Admin

**Comment by Linesmerrill** [comment]
WIll be completed here: https://github.com/Linesmerrill/police-cad/pull/231
