### ISSUE TITLE
Restrictions/revokes/administrative

### ISSUE THREAD

**Issue by IlIKingxVipyIlI** [Linesmerrill/police-cad#177]
**Suggestions/Feature request**

1. Have a list of all viewable emails, usernames or whatever upon joining through invite code.

2. Restrict all new members/users from looking at the invite code.

3. Restrict people/users/emails or in general from using the resources and seeing/interacting with the police and Ems tabs.

**Implementation/Descriptions**
1. When a person signs up, they should have the option/requirement to create a username to be viewable by the owner of the created community cad Upon joining through the invite code for that community. If a username isn’t possible, make a list of the viewable emails. The owner should also be able to revoke people’s invites and or be able to remove them from the so said create community.

2. Only the owner of the created community should be allowed to see the invite code. This would be great if the owner could select certain emails or usernames/users to also see this code! I think that if there was an option to make the invite code invalid or disabled for however long would be good too. 

3. Only the owner of the created community should be allowed to see the police and ems tabs meaning only the owner can search or create citations and everything else. It would also be great if the owner could select certain emails/users to view the tabs and use them themselves. 

**Notice**
I’ve emailed the contact list about this and they said they could possibly bring it up to the MOD team and that I would also suggest and write this up for more of a chance to hopefully make this work. 

In general the owner of the created community should have the options to apply/check mark each of these suggestions to make their cad a bit more restrictive and theN once checked if Anything is, they can create their cad and choose who they want as an official officer, ems or standard staff/administrative role to view and use them!

If you need any other details or furthermore information please contact me! I want to make this as simple and easy yet restrictive!

**Comment by Linesmerrill** [comment]
Hi @IlIKingxVipyIlI ! Awesome suggestion. Thank you for all the details here. We will get this prioritized 👍

**Comment by IlIKingxVipyIlI** [comment]
> Hi @IlIKingxVipyIlI ! Awesome suggestion. Thank you for all the details here. We will get this prioritized 👍

Hey I’ve noticed you’ve added at least one of the suggestions being that we could see people who are in the community & remove them! Don’t know if I was the only to suggest it but great work! Hope to see the rest hopefully fit in, any way to know any updates on this?

**Comment by Linesmerrill** [comment]
@IlIKingxVipyIlI yeah we have received several requests to add this capability, so thank you! The current update we have is just the groundwork that should allow us to implement the additional details listed in this ticket.
