### ISSUE TITLE
Dispatch

### ISSUE THREAD

**Issue by KingsOrchard** [Linesmerrill/police-cad#178]
**Describe the solution you'd like**
An option To be Dispatch 

- 

**Implementation Details**
An option to be a dispatch for police,ems,fire and you can control if there 10-8,10-7,10-6 ect. you can also make callouts such as " 1-M-23 has a 10-11 on Strawberry Ave, no 10-32's needed.

-

**Comment by Linesmerrill** [comment]
Duplicate of: https://github.com/Linesmerrill/police-cad/issues/104
