### ISSUE TITLE
More Infraction's

### ISSUE THREAD

**Issue by Jlambe94** [Linesmerrill/police-cad#181]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- to many people within the community on the C.A.D. are being busted but we have nothing to classify them as, (Ex.. Drug Possession within Roleplay but have no such charge listed within the list we use to issue Citations.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- when ever you can get around to it, i know you are all very busy during these timed keeping safe. (Please Stay Safe & Thank you for all you have done)

**Comment by Linesmerrill** [comment]
Hi @Jlambe94 thanks for suggesting this. We do have the 'Other' option when issuing citations, that is our short term solution to include all types of unique classifications. But I think in the future it would be cool to allow users to add citations to their own community. This would allow for more specific customizations per community.

**Comment by Jlambe94** [comment]
I think that is a Very Good Idea, I can't wait to see how it all works out later on in the C.A.D. You guys are the best.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
