### ISSUE TITLE
Be able to search Civilian without D.O.B

### ISSUE THREAD

**Issue by Gta5Rper** [Linesmerrill/police-cad#182]
You should be able to search up a Civ without the need of the Birth Date, if you search up a plate you will only get the name and last name but no D.O.B either show the Date of birth or just make it optional to put the D.O.B into the Name search Tab, Great system tho,

**Comment by Linesmerrill** [comment]
Hi @Gta5Rper thanks for suggesting this. If you join a community we no longer require you to enter the DOB when searching names. We found that trying to display hundreds of the same names on the page not only hurt website performance, but also creating a negative user experience. This was why we started asking for DOB when searching for a civilian. But once in a community, the number of duplicate names are exponentially less, thus allowing us to remove this added check.

To get started with a community start here: 

> To join or create a community for free, click on the communities button under the top right menu, or at the top right of your screen.
