### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by dj03** [Linesmerrill/police-cad#183]
Would u be able to add a panic button with sound and a sign in for cops like the need to have a call sign etc like a full cad/mdt

**Comment by Linesmerrill** [comment]
HI @dj03 thanks for these suggestions! I broke these out to separate feature requests here:
- Add a panic button with sound.
  - Already have a request here: https://github.com/Linesmerrill/police-cad/issues/100
- Add a sign in for police (to use different call signs)
  - You can now modify your username under the new Accounts menu. To get started click on your username at the top of your screen or under the menu in the top right of your screen.
- Add a full CAD/MDT
  - We have work for that here: https://github.com/Linesmerrill/police-cad/issues/30
