### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by drgood12** [Linesmerrill/police-cad#186]
**Describe the solution you'd like**
[_A log in for Dispatch/Control and a login for Admins_]

- 

**Implementation Details**
[_A way that a dispatch/controller can log in. They should be able to see all 911 calls, all available units, create calls, assign units to the call, create signal 100s that show up on screen. Maybe even text-To-Speech so dispatchers could hear when new 911 calls are, or police can hear when they get a call, or a new BOLO or a signal. Screenshot from Sonoran CAD Dispatch

Admins: A way for admins to see everyone logged in, ban them kick them remove personas/civs, give certain people permissions to access Police/EMS). Let them edit 10-codes and penal codes for servers with different codes._]

- dispatch: https://prnt.sc/scvpyn
Admin: https://prnt.sc/scvq8v

Thanks -drgood12
P.s. maybe add DOT?

**Comment by Linesmerrill** [comment]
Hi @drgood12 thanks for these suggestions!

- Dispatch/controller feature
  - We have a ticket here to track that work already: https://github.com/Linesmerrill/police-cad/issues/100
- Adding access level control for communities
  - We will repurpose this ticket for the work related to this 👍
