### ISSUE TITLE
Civilian Notes/Tags for their ID

### ISSUE THREAD

**Issue by megahalofighter** [Linesmerrill/police-cad#187]
I would love to see an area in the name database called Notes and/or Tags to allow LEO or EMS to know of any special information on a person they are dealing with.

1. I hope to see that LEO can mark people as gang members or a violent person (always shooting/harming people) so other officers can be are aware of their history.
2. Also allowing the EMS to know if there is any medical issue with the civilian they are treating, like medical drugs they are taking and any health issue they may have.
3. Plus when you create the civilian you play, you can add the Notes and/or Tags to your civ to add more to RP from the CAD system.

**Comment by Linesmerrill** [comment]
Medical stuff will be completed here: https://github.com/Linesmerrill/police-cad/pull/231
