### ISSUE TITLE
Civilians across Fire & Police share characteristics 

### ISSUE THREAD

**Issue by Bjorn1435** [Linesmerrill/police-cad#197]
Hey so if just found this amazing, easy basic cad. 
And i would like to see something added in the near future: 
So im gonna try to explain this, when you press Police or EMS/FIRE and make an character ( With the same name as your Civillian character it doesnt automatticly assign Police / EMS / FIRE to your Civillian's occupation. 
Hope someone knows what i mean, if not contact me on discord: Bjorn#5010

-

**Comment by Linesmerrill** [comment]
Hi @Bjorn1435 Thank you for this suggestion. This is not something we have implemented yet but I will let the developers know this is something you would like to see added. Thanks
