### ISSUE TITLE
can we get n panic button thing for the officers in cad that would be nice 

### ISSUE THREAD

**Issue by Mason055** [Linesmerrill/police-cad#199]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/pull/207
