### ISSUE TITLE
Web?

### ISSUE THREAD

**Issue by justinfarmer14** [Linesmerrill/police-cad#2]
Is there any way you can convert this for simple web hosting as im an idiot and but it  would be preferred on cpanel

**Comment by Linesmerrill** [comment]
Hi justinfarmer14,

Unfortunately the database (mongdb) that I have setup with this server is not officially supported on cpanel. In addition, I have no experience with cpanel so it would be difficult for me to try and convert it to make it work. 

The good news is that you can host this server yourself on a free heroku server! You pay $0 per month for free hosting from them. For more info check out this link: https://www.heroku.com

**Comment by justinfarmer14** [comment]
just change the database sir to myqil or mariadb

**Comment by justinfarmer14** [comment]
looks pretty complex to set up tbh

**Comment by Linesmerrill** [comment]
Haha yeah it's definitely more complex than the GUI on cpanel that is for sure. I have a lot of experience deploying apps to Heroku so it was super easy for me to set it up. 

I am not sure what more I can do to help you get your app hosted.. ;(

**Comment by justinfarmer14** [comment]
could you do a video tutorial on how to install it or set it up

becuase with your permission i would love to help this project expand as in have  lot of other use it

**Comment by Linesmerrill** [comment]
Yeah let me see what I can do to get a tutorial all setup and ready for you. Thanks for the feedback.

I look forward to seeing this project grow!

**Comment by justinfarmer14** [comment]
any progress ?

**Comment by Linesmerrill** [comment]
Sorry I have been super busy so I haven’t gotten it all the way finished yet for you. I’ll let you know when I get it all done.
