### ISSUE TITLE
Idea - Implementing a system that allows certain officers to be assigned to calls

### ISSUE THREAD

**Issue by sammkeir** [Linesmerrill/police-cad#202]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- A new system that allows call DESCRIPTIONS (911) to be added and displayed, and for dispatch to be able to assign active officers to them. They can then added/removed, along with the 'code' required to respond to the call. Thanks!!

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Hi @sammkeir ! Awesome suggestion! This is something we are currently working on. Stay tuned for more updates on this in the near future. Thanks!
