### ISSUE TITLE
A Dispatch Option

### ISSUE THREAD

**Issue by brodywesson** [Linesmerrill/police-cad#203]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Id like for LinesPoliceCad to have a full dispatch system and when the Dispatch system is done id like the Police Officer to have a bar above everything where the officers in the community can click 10-8 10-7 10-6 10-11 to show the dispatch what officer is available. this would help this cad a lot if yall could consider it

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- Id like for LinesPoliceCad to have a full dispatch system and when the Dispatch system is done id like the Police Officer to have a bar above everything where the officers in the community can click 10-8 10-7 10-6 10-11 to show the dispatch what officer is available. this would help this cad a lot if yall could consider it

**Comment by Linesmerrill** [comment]
@brodywesson this is a fantastic suggestion! Thank you for letting us know this is some thing you would like to see us add. We will prioritize this.

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/pull/207
