### ISSUE TITLE
Status Updates & More

### ISSUE THREAD

**Issue by FloppyCat43** [Linesmerrill/police-cad#206]
Hello!

First off id like to say thank you for adding the features i mentioned before, they are a great new addition!

One of the main things id like to suggest is a status update, something that shows the status of officers (this being possible due to communities). If they are 10-8, 10-6 or 10-7.

It would be a table with 4 buttons, which have 10-8, 10-7, 10-6 and then the panic button.
The panic button would ask you to input a location and the 10-6 button a reason. (i will provide a sketch to make it a bit clearer). The panic button would play the sound of an actual panic button. 
![Capture](https://user-images.githubusercontent.com/60557889/84119772-88055800-aa3d-11ea-9f00-2cf91a5ee2ed.PNG)

Next time someone logs in as a officer, they are asked to input they're unit number.

If you have any question then feel free to ask, ill gladly answer them!  : )

**Comment by Linesmerrill** [comment]
This is Amazing Detail!! First off thank you @FloppyCat43 for the detail and also the included image. (everyone else needs to take note of this impressive level of detail 10/10!)

Yes this is a great suggestion, and this is actually something we are currently developing right now. If you would be interested to be one of our Beta testers just let us know. We have a Beta implementation our right now with a active dispatch site.

Let us know if that is something you would be interested in and we can get that ball rolling for you. Thanks 😁

**Comment by Linesmerrill** [comment]
Will be completed here: https://github.com/Linesmerrill/police-cad/pull/207

**Comment by FloppyCat43** [comment]
Hello!

Great that you liked it, I was afraid I might have left things a bit up to
interpretation or unclear but glad to see that this wasn't the case.
As for the beta tester offer, simply put, i'd love to be one.

Thanks again.

**Comment by Linesmerrill** [comment]
Fantastic! Can you shoot us an email so we can get all the details sorted?

dev-team@linespolice-cad.com

Thank you!

**Comment by FloppyCat43** [comment]
If you are referring to the email I used to sign up, it's
sadammartin2@gmail.com.
