### ISSUE TITLE
Have a remove charge for civilians for arrests and citations 

### ISSUE THREAD

**Issue by isaacreid16** [Linesmerrill/police-cad#219]
I would like to have the feature of being able to remove charges,citations and arrests from civilians so that rp servers can have court in there servers and be able to take charges off there citations and arrests.

- 

**Implementation Details**
This feature should only be allowed to cops so that civilians can not just use this to give them self’s a clean record. This would be amazing for rp servers that have a functioning court system or want to have one in there group 

-

**Comment by Linesmerrill** [comment]
Hi @isaacreid16 ! Thank you for the suggestion. Our thought process behind what we have is not allowing anyone to game the system. Right now anyone can log in either as a police or civilian. So hypothetically a civilian could log in as a police officer and then clean their entire criminal history without and safe guards. Until we have more of an authorization around the police and civilian dashboards, I don't feel like this would provide a fun and balanced game play.

Let me know your thoughts on that.
