### ISSUE TITLE
More gun options

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#229]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- add a shotgun maybe some new AR or maybe multiple categorys of pistols for the registered weapons

- Maybe possibly snipers maybe or also possibley hunting license

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Adds tons of new weapon options: https://github.com/Linesmerrill/police-cad/commit/93702aefae893adbbc4d1d9076ace0d332cf9a32

**Comment by Polecat2003** [comment]
Add chats so we can talk to each other or a radio
