### ISSUE TITLE
call system for communities

### ISSUE THREAD

**Issue by skully2032** [Linesmerrill/police-cad#240]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

I think it would be cool to have a system where (in communities) civs can create a call and then dispatch can assign and attach officers and fire/ems to the said call. This could be usefull so dispatch can see active calls and what officers are busy and so civs have an easire way of calling 911.  
- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

I would like to see a call center in the civ section so that civs can input the callers name and whats happening along with a location. Along with Dispatch seeing all active calls and being able to send officers to calls and end them.

-

**Comment by skully2032** [comment]
Also p.s. an map that all departments can interact with that has postcodes on would be cool too.

**Comment by Linesmerrill** [comment]
@skully2032 thank you for the suggestions! Yeah I love the active call assignment feature. We are actively working on that right now.

For the second suggestion, we just released a new GTA V Map that can be viewed on any of the dashboards. For more info click here: https://github.com/Linesmerrill/police-cad/pull/244
