### ISSUE TITLE
Communites

### ISSUE THREAD

**Issue by YaboiInk** [Linesmerrill/police-cad#242]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- what would be a cool feature is when you join communites it transfers you civilian, guns, and vehicles to the community without you having to re enter them

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Hi @YaboiInk . Yeah we have been looking into how that would work for some time. The work is tracked here: https://github.com/Linesmerrill/police-cad/issues/190
