### ISSUE TITLE
Bounty Hunter

### ISSUE THREAD

**Issue by Ashton2B23** [Linesmerrill/police-cad#246]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Hi @Ashton2B23 can we get a bit more information on what exactly you would like to see for this?

If this is an occupation that a civilian can have, you can always add that when modifying or creating a civilian.

**Comment by Ashton2B23** [comment]
Hello , what I was thinking was if you made a bounty hunter section you
would have the civ ones but you could see bolos or a section that says
wanted and says there civ name and last known location

**Comment by Linesmerrill** [comment]
Ok I understand. Yeah thank you for the suggestion!
