### ISSUE TITLE
Blocked?

### ISSUE THREAD

**Issue by OfficerStevens** [Linesmerrill/police-cad#247]
It is blocking me from my own CAD Community, it lets me register a name and vehicle in other communities but i cannot manage my own and search names in my own, how do i fix this?
here is the code they told me I needed on the blocked page
Cloudflare Ray ID: 5b202bc4da80fd7e

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi @OfficerStevens thanks for contacting us! We just checked that action inside of our Cloudflare account and could not find any issues with the Ray ID you provided. Can you please try to recreate that behavior today? Also if it occurs again can you attach a screenshot of the error you see.

Thank you for your patience!
