### ISSUE TITLE
Assign officers to calls / Dispatch can make calls

### ISSUE THREAD

**Issue by keeganagt** [Linesmerrill/police-cad#248]
I'm sure a lot of people asked for this feature bug I'm sure a lot of people would l9ve this feature I reccpmend adding it so do otherstraining ♥

**Comment by Linesmerrill** [comment]
Hi @keeganagt . Yes we have received this quite a bit and we are actively working on it. Stay tuned for more updates on this. Thanks!

**Comment by Linesmerrill** [comment]
work is being tracked here: https://github.com/Linesmerrill/police-cad/issues/212
