### ISSUE TITLE
Everytime I click anything it says something went wrong

### ISSUE THREAD

**Issue by MAN1112** [Linesmerrill/police-cad#250]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi @MAN1112 . Thanks for dropping in this bug. Unfortunately you did not leave very much information about the bug you saw. But we did fix a bug relating to loading the website and having issues. Let us know if you are still seeing this by opening a new bug and please fill out all the required information. Thanks!
