### ISSUE TITLE
Civilians are able to type 911 calls and 1 other thing

### ISSUE THREAD

**Issue by 1b17** [Linesmerrill/police-cad#251]
I would like if you could add a thing where Civilians are able to type 911 calls in a create 911 call tab then when they are done the dispatcher is able to get the 911 call under 911 calls.

Also, can you add a system where police are able to make a traffic stop if they are on one in the game and they can type in information about the vehicle, plate, location, occupants in the car, if they have weapons, and why you pulled them over

**Comment by Linesmerrill** [comment]
Hi @1b17. That is a great suggestion! Yeah we will start discussions to start looking into adding this. Thanks
