### ISSUE TITLE
Nothing will work

### ISSUE THREAD

**Issue by HowDoYouShoot11** [Linesmerrill/police-cad#252]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi @HowDoYouShoot11 ! Thanks for creating a bug for this. Can you provide us with a bit more information.

We have this entire form, which it looks like you failed to complete any of it. The form includes all the required information we need to start looking into a bug. With more information we can more quickly debug the issue and then prioritize a fix. Leaving a bug like "Nothing will work" does not give us the proper details we need to address the issue.
