### ISSUE TITLE
I cannot add or register a new civilian car and weapon

### ISSUE THREAD

**Issue by HowDoYouShoot11** [Linesmerrill/police-cad#253]
I am using an iOS device. When I try to click on anything let’s say add new civilian. All it will do is turn the words from white too blue. Nothing will pop up. Like I can’t type anything in and it does the same thing for registering a vehicle and registering a weapon. Please fix this issue I cannot do any role play on grand theft auto 5. This issue does the same thing on my Android phone.

**Comment by Linesmerrill** [comment]
Hi @HowDoYouShoot11 . Thanks for opening this issue. Can you provide us with a bit more information?

- Attach a screenshot of the issue you are seeing
- Provide us with the device you are using
- Which browser on the device are you using
- Steps to re-create the issue on our side

Once we have a few more details from you then we can begin to look into this issue. Thank you!
