### ISSUE TITLE
Add new Occupation section for Civs

### ISSUE THREAD

**Issue by BadboyPsycho2005** [Linesmerrill/police-cad#270]
- Occupation List
Is it okay if you guys add a JOB section so you can create jobs aka. Occupation? Can you make it server wide so you don't have to make the same thing that someone else has made (Make it to Civs in what ever server you are in)
- What to have on it
Occupation name
est. Date
Bankrupt
Description
Address
ownership (only creator can give people roles)

**Comment by Linesmerrill** [comment]
We currently have a place you can specify what job your civilian is currently in. Is this something you currently use?

**Comment by BadboyPsycho2005** [comment]
> We currently have a place you can specify what job your civilian is currently in. Is this something you currently use?

I was thinking of making it like what you have for Civilians, Vehicles, and Firearms

**Comment by Linesmerrill** [comment]
Oh ok I got it! Yeah I'll update the description and title. Great suggestion.
