### ISSUE TITLE
Other Community Members cant see what i have imported

### ISSUE THREAD

**Issue by Foxxii1991** [Linesmerrill/police-cad#278]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- Hello i think i´ve found a bug on your Cad.. other community members cant see what i have imported in the box. we have do it much more but the problem we cant find my friend cant see anything what i have write in the textboxes and what i saved.

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Foxxii1991** [comment]
Hello, 

thanks for your answer, 

yes I´m in a community.
My friend is in the self community.
i´ve register a civilan test person but my friend can´t see it.

[Screenshot 1](https://www.directupload.net/file/d/5921/hevzp4t9_png.htm)

[Screenshot 2 from my friend](https://www.directupload.net/file/d/5921/ovgvfv8u_png.htm)

The website is the landingpage from button civilian.

https://www.linespolice-cad.com/civ-dashboard

**Comment by Linesmerrill** [comment]
Ok perfect! Looks like you are both indeed in the same community. What is the civilian name you have created?

**Comment by Foxxii1991** [comment]
In the moment test 1.

I've deleted all other civilians what I have test 1 ist the first in the
moment

Merrill Lines <notifications@github.com> schrieb am Mo., 24. Aug. 2020,
17:03:

**Comment by Linesmerrill** [comment]
Alright I see a civilian for that community with the following details:
```
firstName:"Test1"
lastName:"Test2"
```

**Comment by Foxxii1991** [comment]
Right that's done today for test but my friend can't see it again only me 😐

Merrill Lines <notifications@github.com> schrieb am Mo., 24. Aug. 2020,
17:14:

**Comment by Linesmerrill** [comment]
This is what I see when I search the name, it seems to show up just fine. Can you double check your friend is spelling the name correctly and is on the police or dispatch dashboard when searching the name?

![image](https://user-images.githubusercontent.com/15384983/91063078-5b93bd80-e5e2-11ea-93b7-89b233f85ab7.png)

**Comment by Foxxii1991** [comment]
He looks in the Civilian database. You mean my friend must search the name
and can't see the Civilian list?

Merrill Lines <notifications@github.com> schrieb am Mo., 24. Aug. 2020,
17:19:

**Comment by Linesmerrill** [comment]
Yeah your friend will not be able to see your civilians on the civilian dashboard. Each civilian dashboard is separate from each other. The only way your friend would be able to see your civilians would be if they were logged in as either a police officer or dispatch and searched the name using the CAD.

**Comment by Foxxii1991** [comment]
Ahh okay I think that's finished our problem 🙈

Merrill Lines <notifications@github.com> schrieb am Mo., 24. Aug. 2020,
17:25:

**Comment by Foxxii1991** [comment]
Hey Linesmerrill,

I love your cad system really. :)
I have a question again. Can u translate it in German? Maybe I can help you
with that. Much German peoples are interested of this.

And think you, this cad can changed in a apk for phones? It's very helpful
for all. I can take u what I mean. I've converted it in a app and build a
website with a little German instruction over the modules and her
functions. (Your name as creator is listed). You can find it on
https://lspd-ems-operation-system.webnode.com/ the link for the apk ist
below the text. I will help to bring this cad and your name, skills under
much peoples.

Merrill Lines <notifications@github.com> schrieb am Mo., 24. Aug. 2020,
17:29:
