### ISSUE TITLE
Cant create and cand delete cars

### ISSUE THREAD

**Issue by bubsgggg** [Linesmerrill/police-cad#283]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi thanks for creating this bug. Can you provide us with a few more details?

- Are you in a community?
- What browser are you using?
- Is this on mobile or computer 
- Do you see an error?
- Provide any screenshots you can of what you see and are trying
