### ISSUE TITLE
add an option for the creator of a community to allow and disallow people to use certain departments 

### ISSUE THREAD

**Issue by TheRandomGamerYT** [Linesmerrill/police-cad#285]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Duplicate of https://github.com/Linesmerrill/police-cad/issues/273
