### ISSUE TITLE
"Something that will tell you the person disabilities as a cop"

### ISSUE THREAD

**Issue by HyperReflexx9** [Linesmerrill/police-cad#291]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- A tab for LEO to be able to see if the subject has been in the hospital for anything.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- a civilian would imput if they have been in the hospital and a reason for such visit. Example: a male was admitted to SSMC (Sandy Shores Medical Centre) after having a heart attack. The civilian would put such in to the tab when creating/editing a civilian character so officers would know the persons medical history, and, should it happen, have to use a non lethal weapon eg: a taser, on the suspect.

**Comment by Linesmerrill** [comment]
What you could do is contact the medial staff and look up their medical history. I feel like that is more what an officer would do in real life.
