### ISSUE TITLE
Dispatch calls

### ISSUE THREAD

**Issue by Monkey2490** [Linesmerrill/police-cad#299]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I would like dispatch to create 911 calls and attach LEO officers to them and i would like signal 100 to have a noise so officers can hear the sound of the signal 100 in affect.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-And add fire and EMS dispatch so dispatch can add them to calls.

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/releases/tag/v2.9.0
