### ISSUE TITLE
report

### ISSUE THREAD

**Issue by PanAdixPL** [Linesmerrill/police-cad#302]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- Hello, I have a proposal to add an option to write reports in the police tab

**Comment by Braeden57** [comment]
This is very vague, please elaborate.

**Comment by Linesmerrill** [comment]
We already allow officers to write reports. This functionality already exists.
