### ISSUE TITLE
Forced to make new accounts upon signin

### ISSUE THREAD

**Issue by HyperReflexx9** [Linesmerrill/police-cad#304]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- when subject tries to log in, he is forced to make a new account everytime, though the account subject is trying to log into exists.

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to 'log in'
2 put in info

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- error saying account doesnt exist

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XR
 - OS: [e.g. iOS8.1] iOS 13.7
 - Browser [e.g. stock browser, safari] Safari
 - Version [e.g. 22] unknown 

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Unable to replicate on my machine. If problem still persists hopefully we can get in direct contact with the person having issues.
