### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SilentFire3968** [Linesmerrill/police-cad#305]
**Describe the solution you'd like**
I would like the dispatcher to be able to make calls for officers, such as 10-11 and so on.

- 

**Implementation Details**
It would be nice for the community owner to also be able to change permissions for everyone so that they can only go onto a select department, instead of having everyone able to just freely go onto police and what not.

-

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/releases/tag/v2.9.0
