### ISSUE TITLE
New map isn't good

### ISSUE THREAD

**Issue by Foxxii1991** [Linesmerrill/police-cad#307]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- the new map isn't good. It's unsharp and when I zoom in then I can't read the zip codes (unsharp).. Device is a huawei P30. 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Braeden57** [comment]
Were you using the interactive map? Or the “for mobile?” Because the interactive map is still being worked on to function properly on mobile devices. Or you can view the popular areas which is a bunch of pictures of popular areas in GTA V

**Comment by Foxxii1991** [comment]
I mean both maps. On my phone I can't read all zip codes.

Braeden Sowinski <notifications@github.com> schrieb am Mi., 16. Sept. 2020,
17:41:

**Comment by Braeden57** [comment]
Do you mind if i get back to you on this? I got a couple classes to do.

**Comment by Braeden57** [comment]
Ok So all maps, Popular Areas Pictures, and the For mobile image. Don't Load properly for you?
