### ISSUE TITLE
Address not showing on license

### ISSUE THREAD

**Issue by NickyScarfo** [Linesmerrill/police-cad#308]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- When playing as a police officer role, the address on a civilian's license does not show up. There are many instances when the license itself does not show up at all. And resetting the civilian does not work

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Thanks for creating a bug for this. Can you check if you are in a community or not? And also if you could post in the address you are using (so we can verify it doesn't have any weird characters that could be causing issues)

**Comment by NickyScarfo** [comment]
Hello, I appreciate you responding. It's any address that I've tried using, no address ever shows up when I look up the person as a police officer. Every address is a postal code and a street name taken directly from the game's map. To also answer your question, I created a community and so far only me and one other person is in it with me.

**Comment by Linesmerrill** [comment]
Perfect thanks for getting back to us. Our team is looking into it and should have a fix shortly. Thank you for your patience.

**Comment by Linesmerrill** [comment]
@NickyScarfo alrighty we have identified the problem and just pushed out a hotfix that should solve the problem. Please refresh your page and let us know if there are any other issues. Thank you!
