### ISSUE TITLE
Create a Callout

### ISSUE THREAD

**Issue by NickyScarfo** [Linesmerrill/police-cad#311]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I would personally like an option for the dispatch role to create a callout for officers on patrol and active EMS units. This could include the reason for the callout, the location of the incident, if a code 1, 2, or 3 response is necessary, and a short summary of the incident. Then an officer can see available callouts in the main police menu, ones that require a code 3 response can be highlighted. An officer could click on the callout and accept it and show themselves in route. 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- The Callout menu could be above the active bolo section, dispatch would have the ability to create a Callout. The callout itself in the menu would include the reason for the Callout, even a radio code for example (417 - Person with a Gun), the location of the incident, if a code 1, 2, or 3 response is necessary, and a short summary of the incident.

**Comment by Linesmerrill** [comment]
We added the ability for Dispatch to create and assign Calls to units in the community. Let me know if there are things you would like to see us add to the current behavior. https://github.com/Linesmerrill/police-cad/releases/tag/v2.9.0
