### ISSUE TITLE
Footer and ad overlay

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#312]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- On the Interactive Map page, the footer is overlayed on the ad

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- The footer should be under the ad

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Acer Aspire Laptop
Windows 10
Chrome

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Thank you @Braeden57 for pointing this out! 🤦 we are actively working to fix this bug.

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/releases/tag/v2.9.2
