### ISSUE TITLE
Penal Codes

### ISSUE THREAD

**Issue by bikkieboi** [Linesmerrill/police-cad#320]
Hello,

I think it would be a great idea to add penal codes to Lines Police CAD. It would be very useful for many reasons, such as:

-Helping people learn their laws so they don't start an unlawful traffic stop
-Having a specific reason to pull over or arrest someone
-Helping people to get out of an unlawful traffic stop

I don't personally have any penal codes for you to use but if you use the contents from the citations section and also look up California law, I think it could come along quite nicely. 

I think it's the one thing that is needed for the CAD that hasn't already been added. It would fit in perfectly and make it even better and more legit.

Thanks for reading,

bikkieboi.

**Comment by Linesmerrill** [comment]
Yeah this is a fantastic suggestion! I've just been trying to source a Penal codes reference we could use. Do you happen to have some?

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/pull/368
