### ISSUE TITLE
Calls

### ISSUE THREAD

**Issue by RyanLatham02** [Linesmerrill/police-cad#321]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I love the dispatching system you guys have but I feel like it missing the ability to make calls and add other active officers to the calls. 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/releases/tag/v2.9.0
