### ISSUE TITLE
Address not showing up on License

### ISSUE THREAD

**Issue by NickyScarfo** [Linesmerrill/police-cad#328]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- When searching a civilians name in the police ped database, no matter what is logged for the civilian's address, it will not show up on the driver's license when the person's info show up. 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- Go to: Name Database
Go to: *type in name*
*No Address shows up even for previously logged civilians*

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Thank you for reporting this bug. 

- Was this on the Dispatch Dashboard or the Police Dashboard?
- Are you in a community or not?
- Was this on mobile or desktop browser?
- Can you try creating a civilian with a new name "John Smith" with an address "1234 N Main St" and see if john smith shows up after searching?

**Comment by NickyScarfo** [comment]
Hello, thank you for getting back to me and reviewing my report. The bug I experienced was on both Police and Dispatch Dashboards. I am in a community. I attempted to retype information for already existing civilians and creating new ones all together to no avail.


Sent from Yahoo Mail for iPhone


On Tuesday, October 27, 2020, 9:19 PM, Merrill Lines <notifications@github.com> wrote:




Thank you for reporting this bug.
   
   - Was this on the Dispatch Dashboard or the Police Dashboard?
   - Are you in a community or not?
   - Was this on mobile or desktop browser?
   - Can you try creating a civilian with a new name "John Smith" with an address "1234 N Main St" and see if john smith shows up after searching?

**Comment by Linesmerrill** [comment]
Thank you for the additional information. Can you take a look at our video on creating a civilian and viewing the address? https://youtu.be/NNhN9-wV3T8. If you can follow those steps and if you still have issues could you please send us some screen shots of what you are seeing? (you should be able to upload them directly to this chat)

Thanks!
