### ISSUE TITLE
On the cad can you guys put on the police thing superviser panel and on the home page were you click police fire dispatch put a admin thing there and for the ticket make it show up like it is a real ticket wirtten out and ad on the arrest with chargers please

### ISSUE THREAD

**Issue by TheGamerSheriff23** [Linesmerrill/police-cad#336]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
I split this out into new tickets as separate feature requests. If you could fill out all the details in the ticket that would be great! (fill out the description section and the implementation details)

- Police Supervisor Panel: https://github.com/Linesmerrill/police-cad/issues/337
- Ticket display as real Ticket: https://github.com/Linesmerrill/police-cad/issues/338

**Comment by TheGamerSheriff23** [comment]
for the ticket make it like let me see here  like this for tickets ill
think about something for supervisor panel
[image: image.png]
