### ISSUE TITLE
Show Citation as a real looking citation

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#338]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Please fill out what you would like to see here, if you have an example ticket we can reference please include that in this ticket.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Coxy-cop11** [comment]
Dude this guy😂

**Comment by Coxy-cop11** [comment]
JUST STOP 😂

**Comment by Coxy-cop11** [comment]
There’s no point of this

**Comment by Coxy-cop11** [comment]
All that would do is make things very annoying

**Comment by Coxy-cop11** [comment]
Wait never mind
