### ISSUE TITLE
Give Police Officers the power to revoke a Firearm’s License

### ISSUE THREAD

**Issue by NickyScarfo** [Linesmerrill/police-cad#342]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- When a police officer looks up a person in the ped database. The police officer would have the ability to revoke a firearm's license from someone. Similar to how an officer can revoke a drivers license.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Coxy-cop11** [comment]
Yeah that’s pretty good

**Comment by Coxy-cop11** [comment]
Yeah they should do that
