### ISSUE TITLE
Only show on duty cops

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#343]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 
Have a list showing officers on duty, making it easy for dispatch to navigate
**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- In the dispatch, it shows all officers online and offline. There should be a section only showing online. So dispatch doesn't have to scroll through pages of off duty cops.

**Comment by Coxy-cop11** [comment]
No that’s annoying
