### ISSUE TITLE
Play Sound when your assigned to a call.

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#344]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- When Dispatch assigns an officer to a call. It will play a sound on the officer client, notifying them they have been assigned to a call.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
+1 from CrazyAbskeababes in Discord
