### ISSUE TITLE
Civs can click 911 button and call is created to dispatch

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#348]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Might i also suggest a "Call 911" button on the civ tab. Then a dashboard can pop up with a form to fill such as where and what is happening. Then it could go to an "Open Calls" Sector in dispatch and they can notify units

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Coxy-cop11** [comment]
Dude you need to put more effort in to your requests man
