### ISSUE TITLE
Community Code doesn’t work

### ISSUE THREAD

**Issue by TheDearLeadersDoctor** [Linesmerrill/police-cad#358]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- When ever I go to put in the community code in the join community section it says that there is no community with that code.

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- It would place me in the server of which the code belonged to

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hello thanks for opening this bug ticket. Can you please make sure there are no spaces when entering the code? If that does not resolve the issue, can you try creating a community, then leave the community you created and then try rejoining it?

**Comment by TheDearLeadersDoctor** [comment]
Sorry that didn’t work either is there any other way

**Comment by Linesmerrill** [comment]
Ok so you cannot create a community either?

**Comment by TheDearLeadersDoctor** [comment]
Sorry I should have been more clear I created a community then left it then retried to join the other one but it didn’t work
