### ISSUE TITLE
New map 4k with more numbers.

### ISSUE THREAD

**Issue by MatheusSilvaBR** [Linesmerrill/police-cad#362]
New map file that could be in CAD: 

[Full PNG.zip](https://github.com/Linesmerrill/police-cad/files/5629992/Full.PNG.zip)

**Comment by Linesmerrill** [comment]
Current Map Postal Codes:

![image](https://user-images.githubusercontent.com/15384983/101549341-bde2b500-396a-11eb-828b-95fbf927af50.png)


Requested new map Postal Codes:
![image](https://user-images.githubusercontent.com/15384983/101549379-cc30d100-396a-11eb-8119-b98460e3d0da.png)
