### ISSUE TITLE
911 calls

### ISSUE THREAD

**Issue by Coxy-cop11** [Linesmerrill/police-cad#363]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Add a 911 system into the cad

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- New page/tab in the civilian menu, where they can report a problem etc, to the dispatcher.
- Dispatcher can see the 911 call on a new 911 tab.
- they can then make it into a call etc.
   Something like that pls. :)

**Comment by NickyScarfo** [comment]
I feel like a 911 Call option for civilians would be super immersive and pretty cool to see. I hope this is a feature that gets added.
