### ISSUE TITLE
DISPATCH FOR FD/EMS

### ISSUE THREAD

**Issue by Coxy-cop11** [Linesmerrill/police-cad#365]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- adds a tab in the side menu for fire/ems in dispatch operations

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- new tab where it’s like the current dispatch for police, but make it work for fire/ems
- you can see the players username just as you can for the police
- new fire/ems radio codes/10 codes as well as new status buttons for fire/ems
Thanks :)

**Comment by Linesmerrill** [comment]
+1 from CRAZYABSKEABABES in Discord

**Comment by Linesmerrill** [comment]
+1 from PinballGamer420 in Discord

Ideally it would look something like this:

![image](https://user-images.githubusercontent.com/15384983/104096107-b78c7500-5257-11eb-9637-402622e6f797.png)
