### ISSUE TITLE
Show vehicles on name look up

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#372]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- when looking up a name in the police dispatch it would also show the associated vehicles with that name￼

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Braeden57** [comment]
Already Done
