### ISSUE TITLE
I need to switch servers but how

### ISSUE THREAD

**Issue by tyler446** [Linesmerrill/police-cad#382]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Braeden57** [comment]
Can you please be more specific? Its hard to help you with a vague request.
