### ISSUE TITLE
UK-Code System

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#387]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- The ability to switch between American and UK 10 code systems.
   This would be very useful as I do see a large UK player base, especially on xbox.
**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Do we know what these UK codes look like? Or would it make more sense for the community admin having the ability to just create their own 10 codes?

**Comment by Braeden57** [comment]
I think it would make more sense to have a custom 10-Code System. This also makes the cad more universal rather than the standard North American 10-Codes.
