### ISSUE TITLE
Only Show Officers in Dispatch Dashboard

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#389]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- In the Dispatch Dashboard. The list of members, should only show people who are officers.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- How can this be accomplished? This can relate to the dashboard lock. Preventing a group of people (selected by the community admin) from accessing the Police Dashboard. The people who can access the Police Dashboard are in a separate list. This Separate List could then be the list used in the Dispatch Dashboard to show ONLY police officers.

Maybe, in the Manage Community tab. The admin can mark specific users as an "Officer" the people who are marked as "Officer" can have access to the Dispatch / Police Dashboard. And those who are not marked as "Officer" can only access the Civilian Dashboard. The "Officer" mark can be as easy as a check mark on the list of all members in a community.

**Comment by Linesmerrill** [comment]
Yeah i like this suggestion! I think we should work on something like this next!
