### ISSUE TITLE
Führerschein entziehen 

### ISSUE THREAD

**Issue by Defuserhd** [Linesmerrill/police-cad#404]
Hallo 

Ich habe folgendes Problem ich kann keine Führerscheine entziehen ich kann sie gültig machen aber nicht widerrufen. Ich habe mein Account neu erstellt und da geht es auch nicht 

Hoffe auf eine positive Rückmeldung

**Comment by Braeden57** [comment]
Hallo, danke für deinen Bericht. Wenn dies falsch formuliert ist, tut es mir leid, da ich einen Übersetzer benutze. Versuchen Sie, die Lizenz im zivilen Dashboard zu widerrufen, während Sie einen Zivilisten erstellen oder bearbeiten? Oder liegt das Problem auf dem Polizei-Dashboard beim Versuch, eine Zivilistenlizenz zu widerrufen?

**Comment by Defuserhd** [comment]
Ja es gibt ja den Button Führerschein Lizenz entziehen alle können es außer
ich ich drücke auf den Button nix passiert wenn er widerrufen wurde und ich
den wieder gültig machen soll geht es

Braeden Sowinski <notifications@github.com> schrieb am Mo., 22. Feb. 2021,
23:11:

**Comment by Braeden57** [comment]
In Ordnung, können Sie mitteilen, was Sie für den Zugriff auf Linienpolizei-Cad verwenden. Beispiele sind ein Telefon, ein Desktop oder ein Tablet. Wenn Sie auch Ihr Betriebssystem bereitstellen können. Beispiele sind Windows 10, Mac OS, Android. Und den Browser, den Sie verwenden. Beispiele sind Google Chrome, Safari, andere. Dies kann uns helfen, herauszufinden, woher das Problem kommen kann.

**Comment by Braeden57** [comment]
In Ordnung, können Sie mitteilen, was Sie für den Zugriff auf Linienpolizei-Cad verwenden. Beispiele sind ein Telefon, ein Desktop oder ein Tablet. Wenn Sie auch Ihr Betriebssystem bereitstellen können. Beispiele sind Windows 10, Mac OS, Android. Und den Browser, den Sie verwenden. Beispiele sind Google Chrome, Safari, andere. Dies kann uns helfen, herauszufinden, woher das Problem kommen kann.

**Comment by Defuserhd** [comment]
Ein Telefon

Andere können es aber auch über Handy

Braeden Sowinski <notifications@github.com> schrieb am Mo., 22. Feb. 2021,
23:21:

**Comment by Braeden57** [comment]
Vielen Dank, ich melde mich so schnell wie möglich bei Ihnen. Hoffentlich habe ich das Problem gefunden und kann Ihr Problem lösen.

> Ein Telefon Andere können es aber auch über Handy Braeden Sowinski <notifications@github.com> schrieb am Mo., 22. Feb.

**Comment by Braeden57** [comment]
Können Sie einen Screenshot des Problems bereitstellen? Es wäre wirklich hilfreich, um das Problem zu bestimmen. Vielen Dank

**Comment by Defuserhd** [comment]
Ich kann Ihnen auch ein kurzes Video schicken

Braeden Sowinski <notifications@github.com> schrieb am Mo., 22. Feb. 2021,
23:46:

**Comment by Braeden57** [comment]
Ja das wird großartig
> I can also send you a short video Braeden Sowinski <notifications@github.com> wrote on Mon., Feb. 22, 2021, 11:46 pm:

**Comment by Defuserhd** [comment]
Ich habe gute Nachrichten es geht wieder Ich habe es gerade versucht und es
geht💯

Defuser Hd <mauricewetzel17.01.2003@gmail.com> schrieb am Mo., 22. Feb.
2021, 23:58:

**Comment by Braeden57** [comment]
Das ist toll zu hören, wenn Sie noch etwas brauchen, können Sie mich gerne fragen. Ich war froh zu helfen.

> I have good news it goes again I just tried and it works💯 Defuser Hd <mauricewetzel17.01.2003@gmail.com> wrote on

**Comment by Defuserhd** [comment]
Danke

Hätte noch eine Sache könnte man das Strafenkatalog übersichtlicher machen?

Braeden Sowinski <notifications@github.com> schrieb am Di., 23. Feb. 2021,
00:03:

**Comment by Braeden57** [comment]
Ich glaube, das wurde angefordert, ich werde es dem Protokoll hinzufügen, damit es eines Tages hinzugefügt wird. Danke für den Vorschlag.

> Thank you Would there be one more thing that could be done to make the catalog of penalties clearer? Braeden Sowinski
