### ISSUE TITLE
department in justice

### ISSUE THREAD

**Issue by jayden-1A-81** [Linesmerrill/police-cad#407]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Braeden57** [comment]
Hi, thanks for your request.
Please add a description of detail so we can have a better understanding of what you would like to see.
