### ISSUE TITLE
Website Cookie notification overlay problem.

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#418]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- When viewing the rules on the site. The `This website uses cookies to improve your experience. Learn More` and the `Got it` Button are hidden and are not accessible behind the top navigation menu.

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to https://www.linespolice-cad.com/rules
2. See the error

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- This problem prevents users from being able to click the "Got it" button making it ineffective.

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

![error-1](https://user-images.githubusercontent.com/48144618/111890041-2fd38d00-89a3-11eb-92c2-42f076d44ed0.png)
![error-2](https://user-images.githubusercontent.com/48144618/111890043-3104ba00-89a3-11eb-9022-c32a5026c41e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Microsoft Edge
 - Version: Chrome Version 89.0.4389.90 (Official Build) (64-bit)
                 Microsoft Edge Version 89.0.774.57 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Iphone 8+
 - OS: IOS 14.4
 - Browser: Safari

**Comment by Linesmerrill** [comment]
Good catch here! Let's fix that!

**Comment by Linesmerrill** [comment]
Removed the overlay on the rules page
