### ISSUE TITLE
Add a “File Police Report” Feature

### ISSUE THREAD

**Issue by NickyScarfo** [Linesmerrill/police-cad#424]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I know it is probably difficult to add a "Call 911" feature to the CAD. So this is my suggestion for an alternative. Give Civilians the feature to "File a Police Report" it would be an alternative to have a "Call 911" Feature. Civilians would be able to press "File Police Report" and a form to fill out would pop up on the screen where they would have to provide:

- Their name 
- The location of where the crime was committed or where it is currently happening (ie: Landmark, Street Address, Area Code, etc)
- The names of the people involved or a physical description of who was involved 
- And a Summary as to what happened and/or what is actively happening 

Once the civilian submits this report, it would show up in the Dispatch and Police Dashboards in their own category. Dispatch would have the ability to read the reports and "Create A Call" for Police to respond to the location the civilian provided. Police would also be able to see these reports in their dashboard and respond to them accordingly with dispatch as well. Dispatch would also be able to judge whether or not EMS/Fire is required to respond as well. Overall, I hope this feature gets added, I believe it could benefit greatly.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by ColtonM395** [comment]
This would be great

**Comment by Linesmerrill** [comment]
Yeah I think we could add a "call 911" button for civilians in the new side menu, and allow these to be routed to dispatch. Great suggestion!

**Comment by Linesmerrill** [comment]
Can combine this with: https://github.com/Linesmerrill/police-cad/issues/433.

**Comment by Linesmerrill** [comment]
Adds a 911 button for civilians: https://github.com/Linesmerrill/police-cad/pull/464
