### ISSUE TITLE
Call 911

### ISSUE THREAD

**Issue by 7ADAM15** [Linesmerrill/police-cad#433]
Multiple members in my roleplay community have been reaching out to me in regards to a feature they would like to see!

Many members of mine who (Don't) want to use discord to call 911 (Dispatch) want to be able to submit a call from their civilian operations straight to dispatch operations!

I believe this would be a great **Update/Feature** to have not only does it make our roleplay situations roleplay quicker than they are now. But it gives our dispatch something extra to look forward to. Many other cad software we have used before have had this feature and we believe that this would make your system a whole lot better.

if you want we can give you a detailed report of what this feature could do and why it's worth a feature to add we can:)

Kind Regards,
Mission Row Enforcement, Owner

-

**Comment by Linesmerrill** [comment]
Yeah I like this idea! Let me tag this.
