### ISSUE TITLE
Hunting and fishing

### ISSUE THREAD

**Issue by GySGTPlower** [Linesmerrill/police-cad#434]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- add to the civilian side hunting and fishing licenses 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- when you would make a civilian or edit one you could add either or both licenses so the tickets on the police side would make sense

**Comment by Linesmerrill** [comment]
Work can be combined with this: https://github.com/Linesmerrill/police-cad/issues/457
