### ISSUE TITLE
Community Management

### ISSUE THREAD

**Issue by McDazzzled** [Linesmerrill/police-cad#435]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Add the ability for a community owner to manage/change nicknames and callsigns for it to be more organized for the dispatcher.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
💯 agree
