### ISSUE TITLE
edit button for arrest records

### ISSUE THREAD

**Issue by milkycowsack** [Linesmerrill/police-cad#436]
**Describe the solution you'd like**
[no one seems to be able to edit arrests after it has been submitted on the person. would be extremely helpful.]

- 

**Implementation Details**
[we have new recruits that often make mistakes so if one of them messes up when adding an arrest to someone we are not able to fix it.]

-

**Comment by Braeden57** [comment]
Im going to remove this request as after a arrest report is created, it shall not be edited. Otherwise its not really a record if you can update it. If this is for a mistake made in a report I would suggest double checking before you create the arrest report.
