### ISSUE TITLE
Add configurable license creation

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#457]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- commercial drivers license or other special licenses

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by fazediesel619** [comment]
Add certain specialized vehicule liscenses like Pilots License, Hazardous Chemicals License, Commercial Drivers License, etc. Along with configurable restrictions like a kurfew, weight limits, Passenger restrictions.

**Comment by fazediesel619** [comment]
The Police and Dispatch are allowed to add and remove restrictions for traffic violations
