### ISSUE TITLE
Autojoin community with generated link

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#458]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- if u make a community be able to generate a link so u can send me the link  and they auto join the community

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Braeden57** [comment]
I just thought of a easy way to do this, when you own a community, you can have a button to generate the link. It will be something along the lines of `https://www.linespolice-cad.com/join-community?id=community_generated_id`. The `/join-community` will trigger a function to set the current users active community to the own specified as a url parameter. This will of course require the user to be logged in before hand. Once the function successfully has the user join it can just redirect them to the `communities-dashboard`
