### ISSUE TITLE
filter officers

### ISSUE THREAD

**Issue by TanguyOrtegat** [Linesmerrill/police-cad#46]
What would be great for the commandand to give money each week to his officers, is to have a report/ list with name filter who did want and gave what.

The commandand will then see who worked well, and who didn't.

**Comment by Linesmerrill** [comment]
Hi @TanguyOrtegat thanks for suggesting this! This will probably be a feature request for the new Dispatch CAD, since that would be more related to a single department. Ill tag this for that Milestone and pop it in the backlog. 👍

**Comment by Linesmerrill** [comment]
Releated to https://github.com/Linesmerrill/police-cad/issues/43
