### ISSUE TITLE
incident Reports

### ISSUE THREAD

**Issue by ColtonM395** [Linesmerrill/police-cad#460]
Hi i have used this app for many years. The experience has been amazing 
i would love for your great team to implement things like incident reports, have an option to put a note on a person for gang involvement and  be able to note the person is known for fleeing. 
- 

When I rp there are a lot of  things I wish I could make incident reports for. I think this would be amazing and add a lot more depth to the app. I also think leaving notes on a person after a pursuit or scene with them. you can leave things like ''had previously involved in gangs. You guys keep up the good work!

-

**Comment by Linesmerrill** [comment]
Ok for an incident report form. What It would usually have is the details of the event. Then would have the persons name dob, and info. There would also be postal code of where the incident took place.  There would also be a witness box if there were any and there contact info (name) and a police officers badge #. If you want I could send an example of a incident report form in the chat
There's a lot more detailed incident report forms, this one is the simplest and a lot easier to write and for you guys.

![d2f18ff2b44838425abc4e6583bd1d2b](https://user-images.githubusercontent.com/15384983/118574261-e8664480-b738-11eb-8f4d-68e964de7cb3.jpeg)

**Comment by Linesmerrill** [comment]
> In real life report are stored in files. What I would do is every time you create you it generates a  report number. And you can search those numbers up. Although I can see how that goes wrong. I'm not to sure I'll think of some stuff and give suggestions
Or make a place to look at all the reports made in the community
> Yeah maybe if you make like a page to see all the previous reports and if you search are civilians name up and they report was linked to them have an option to see it on their civilian

- Colton
