### ISSUE TITLE
Missing Assigned Call Details Bug

### ISSUE THREAD

**Issue by Braeden57** [Linesmerrill/police-cad#469]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- As I was trying out the new 911 call update. I noticed: A civilian creates a 911 call. This gets sent to dispatch. After Dispatch receives the call, he then assigns officer(s) to the call. Those officer(s) in the `police-dashboard` can view the call. But no details are shown.

- It only seems to happen with 911 calls. I tried creating a call straight from the `dispatch-dashboard` and assigned an officer, but this time the details were appearing.

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to `civ-dashboard` and create a 911 call
2. In the 'dispatch-dashboard' assign an officer the call
3. Go to 'police-dashboard' and view the call.
4. See error: No details are shown.

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- The call details should be shown, but in this case they are blank.

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

I create the 911 call
![error1](https://user-images.githubusercontent.com/48144618/119238264-5a9ea680-baf6-11eb-8ace-dfc3114fcd58.png)

I assign an officer to the call
![error2](https://user-images.githubusercontent.com/48144618/119238265-5b373d00-baf6-11eb-9fcd-ad1314af5f01.png)

The officer can open the call assigned but no details are shown
![error3](https://user-images.githubusercontent.com/48144618/119238266-5bcfd380-baf6-11eb-8d43-ee026794be8b.png)

**Comment by Linesmerrill** [comment]
Good catch here!! Looking into it right now

**Comment by Linesmerrill** [comment]
Bugfix here: https://github.com/Linesmerrill/police-cad/pull/470. Thanks for catching this @Braeden57
