### ISSUE TITLE
1 login

### ISSUE THREAD

**Issue by TanguyOrtegat** [Linesmerrill/police-cad#47]
A great feature would be to not login each time you switch from civil / police dashboard. Once logged in, you can access both without logging in again. That would spare a lot of time !

Thanks

**Comment by Linesmerrill** [comment]
Hi @TanguyOrtegat Yeah 100% agree with you on this! We will prioritize this in our backlog.

**Comment by Linesmerrill** [comment]
Here is the fix for this, so once you are logged in you can access all options without having to re-login. https://github.com/Linesmerrill/police-cad/pull/52

Thanks for the suggestion here ⭐️

**Comment by Linesmerrill** [comment]
Fixed and deployed ✅

**Comment by TanguyOrtegat** [comment]
@Linesmerrill thank you for this !
