### ISSUE TITLE
Character

### ISSUE THREAD

**Issue by MiniLiber8ed** [Linesmerrill/police-cad#476]
I cannot delete character’s, it physically won’t let me, I don’t like having 100 characters piled up, plz fix thanks

**Comment by Linesmerrill** [comment]
Hi @MiniLiber8ed can you give us a bit more details on the issue you are encountering?

1) What operating system are you using?
2) Mobile or Desktop/Laptop
3) Step by step instructions we can use to replicate the issue
4) Have you tried refreshing the page?
5) Have you tried using a different browser?
6) Can you create civilians?

**Comment by Linesmerrill** [comment]
Update: We have identified the issue as only occurring on mobile devices. We have found the issue on both Safari and Google Chrome on an iPhone device.

We are deploying a patch right now that should help to remove the issue. We will update this ticket again once the issue has been fully resolved.

**Comment by Linesmerrill** [comment]
Issue has been resolved. Should now work properly on all mobile devices now.
