### ISSUE TITLE
Can't search names or plates it is showing no name/ vehicle found on multiple devices. 

### ISSUE THREAD

**Issue by officerhowreya** [Linesmerrill/police-cad#480]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi @officerhowreya thanks for creating a bug for this. Can we get a bit more information around when you were seeing this issue?

1) Was this on mobile or desktop browser?
1) Are you currently in a community?
1) Are you searching new civilian names and plates or older civilian names and plates?
1) Can you provide some steps to recreate the issue?
1) Please include some screenshots of the issues you are seeing

Once we have these details we will be able to more quickly find and help resolve your issues.

**Comment by officerhowreya** [comment]
We are using both mobile and computer systems using a community code. We
just went into search name and plate and it gave an error message of plate/
name not found in police database.

**Comment by Linesmerrill** [comment]
Can you try creating a new civilian and seeing if it shows up after a name search?

**Comment by officerhowreya** [comment]
Yes that worked thank you

**Comment by Linesmerrill** [comment]
Awesome! Yeah if you are searching by plate number and try clicking on the civilians name in that window, the civilian could no longer exist - so you would see the error message stating that no matching civilians were found.

But as long as the civilian exists, it should display the proper record back to you.

If you have any other issues, feel free to create another bug ticket here and we will address it. Thank you 👍

**Comment by officerhowreya** [comment]
👍💙
