### ISSUE TITLE
New Licenses

### ISSUE THREAD

**Issue by SowinskiBraeden** [Linesmerrill/police-cad#485]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Add Civilians the ability to have, Motorcycle, licence, etc.
- Add the ability to add small image to your licence.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Add it to where Civilians can make it to where if there civ has a pilot license and if so they could also make it to where it could get revoked by the police
