### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by TanguyOrtegat** [Linesmerrill/police-cad#49]
i don't know when this happens, but when i came back to my server i saw this error (multiple times). i don't know how to fix it. Maybe you do ?

BadRequestError: request aborted
    at IncomingMessage.onAborted (C:\Users\Administrator\Desktop\police-cad-mast
er\node_modules\raw-body\index.js:231:10)
    at IncomingMessage.emit (events.js:189:13)
    at abortIncoming (_http_server.js:449:9)
    at socketOnClose (_http_server.js:442:3)
    at Socket.emit (events.js:194:15)
    at TCP._handle.close (net.js:597:12)

**Comment by Linesmerrill** [comment]
@TanguyOrtegat Thanks for reporting this issue. It looks like the server was receiving a bad request. Was the server just idle while you saw this or was it receiving some traffic? Also I have only ran this server on Linux and Mac devices so not 100% sure what side effects there could be running this on a Windows operating system.

**Comment by TanguyOrtegat** [comment]
i ll try to figure it out. Will repost when i see something in particular

**Comment by TanguyOrtegat** [comment]
I think it was due to malfunctioning of dropdown boxes that you did remove in this release
