### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by rco-titus** [Linesmerrill/police-cad#493]
Most Communities use discord, _You can set it up where they link their community to the bot with their community code._ The bot would correspond between discord and the website.

You should be able to basically do anything with the bot. **Receive 911 Calls, Create Calls, Change your Status, Search Names/Plates etc.** 

Even System Logging. Create Logging Options which can be linked to different discord channels. you can have Login Logs, Incident Logs _(Ticket/Warning/Arrest.)_ you could go as far as logging database searches. _(Name Searches, Firearm, Plate etc.)_

**Comment by Braeden57** [comment]
This is possible but will take some time. If any progress is made I will be sure to let you know.
