### ISSUE TITLE
Ems medical record 

### ISSUE THREAD

**Issue by Jbern1997** [Linesmerrill/police-cad#495]
**Describe the bug**
[Ems medical records nothing pops up and we’ve made a few]

- 

**To Reproduce**
[_Looks up medical history  nothing shows up_]

**Expected behavior**
[_Expected to add medical history for patient ._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Braeden57** [comment]
Please fill out the bug report form with as much detail so we can find and fix the bug.
