### ISSUE TITLE
Warrants not visible

### ISSUE THREAD

**Issue by 23lnelson** [Linesmerrill/police-cad#500]
**Describe the bug**
[_A clear and concise description of what the bug is._]
When a name is searched it will only say "click warrant to clear" but it won't show the active warrants
- 

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Set warrant on suspect
2. Search suspect name in name search
3. Look for warrant 
**Expected behavior**
[_A clear and concise description of what you expected to happen._]
It should show the warrants
- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- Device: Samsung Tab 3
- OS: unknown how to find
-  Browser: Chrome
**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Thanks for creating this. Have you made sure that you are in the same community as the civilian?

I.e: does the civilian show up, but it just doesn't have the most recent warrant?

**Comment by 23lnelson** [comment]
Yes the civ will show up
