### ISSUE TITLE
I have an account and now when I try to sign in it wont let me and I'm putting in the exact same email and password as before.

### ISSUE THREAD

**Issue by F3arles77** [Linesmerrill/police-cad#507]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hi @F3arles77 we apologize for any inconvenience with your account. Can you please email us at support@linespolice-cad.com from the email address you are having issues with. We will then send a reset link to get your account reset.
