### ISSUE TITLE
Call Sound Notification

### ISSUE THREAD

**Issue by FTASunset** [Linesmerrill/police-cad#526]
Hey Developers Of Lines Police Cad 
@ExpDev07 @ayushmishra2005 @Linesmerrill @SowinskiBraeden

- I've Been Using Your Amazing Cad For A While Now And Was Wondering If You Where Able To Add A Sound Affect Every time You Get A 911 Call Or Get Assigned To A Call As An LEO

- I've Found It Quite Frustrating Every time I Miss A 911 Call Because There's No Sound Notification
- I've Also Found It Even More Frustrating That When I'm A LEO I Also Miss A Call Because There's No Sound Notification

Yours Sincerely FTA Sunset

Please Feel Free to Email Me For Any More Ideas sunsetgaming@gmail.com

**Comment by SowinskiBraeden** [comment]
Thanks for your suggestion @FTASunset, Ill be sure to let you know if any development on this request is made. I believe this has been requested several times, and I'll see to it that this can be implemented. Thanks

**Comment by ayushmishra2005** [comment]
@FTASunset Why have you tagged me? I am not working on this project.

**Comment by Linesmerrill** [comment]
> @FTASunset Why have you tagged me? I am not working on this project.

Yeah sorry about that, probably a mistake tag. You can disregard. Thanks.
