### ISSUE TITLE
Fire and EMS section remake

### ISSUE THREAD

**Issue by skully2032** [Linesmerrill/police-cad#533]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I would like to see the Fire and EMS section get a remake. Seeing as the Police, Dispatch and CIV sections have all been updated.

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- Like the Police section a call function would be nice as well as the ability to set as 10-7, 10-8, 10-41. ect. Also the ability for the callsign and maybe the personel type (figher fighter or paramedic) to show up in dispatch so that they can also be attached and dispatched to calls. Also the implementation of a panic button would also be a nice cherry on top.

**Comment by Linesmerrill** [comment]
Allow dispatch to create/assign calls to Fire/EMS

**Comment by SowinskiBraeden** [comment]
This is now done
