### ISSUE TITLE
delete a ticket

### ISSUE THREAD

**Issue by legendxenn** [Linesmerrill/police-cad#547]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[so is there a way to be able to make the dispatch able to delete tickets that are given to a user in a community, or is it not possible? ]

-

**Comment by SowinskiBraeden** [comment]
This isn't exactly relevant as a ticket is a **permanent** record. The only use I see for this is a ticket accidently being submitted under a civilians name, but that would have to go through the whole write up process so I doubt the mistake is made often.
