### ISSUE TITLE
Police to sign on as Supervisors

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#578]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- Can you add a feature for police to sign on as supervisors so that way it shows who's all a supervisor for the police and for Rp
- Yes and a feature to allow supervisors to be shown different from regular

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by SowinskiBraeden** [comment]
He also says, _ a unique identifier to show them in another list on the dispatch dashboard_
