### ISSUE TITLE
Cad not showing license info for police

### ISSUE THREAD

**Issue by Jeffcool43** [Linesmerrill/police-cad#592]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- when you search for people
- The license dos won’t show any info 

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to '..search name.'
2. Click on '.then click next...'

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- if dose it anytime we put in names on the cad for police 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]
![F3B2571B-E0AE-40BF-948C-F70BA2F3117F](https://user-images.githubusercontent.com/99045375/152588268-d96a9ff8-12f7-44a8-980c-837663763722.png)

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Thank you for bringing this to our attention. Taking a look now.

**Comment by Linesmerrill** [comment]
Found a bug where we were passing an empty variable. This has been fixed and released.
