### ISSUE TITLE
I have a few questions

### ISSUE THREAD

**Issue by FrostbiteYoutube** [Linesmerrill/police-cad#593]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I was wondering if you could create a cad for Emergency Response Liberty County on roblox. It would be so much help for my community since we can't afford a Sorna

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by SowinskiBraeden** [comment]
Can you explain this in more detail please?

**Comment by FrostbiteYoutube** [comment]
Response
    I am one of the head moderators for  Louisville Metropolitan Community
Roleplay.  But we play Emergency Response Liberty County on Roblox. We
can't afford another cads because they're too pricey.
    So we were wondering if you guys could make us a custom CAD with the
map of that Roblox game. Working like it does on GTA. But we run our own
private server with custom vehicles and everything.
     It would just really help make our role play experience better and
make my YouTube videos better.
Sincerely Frostbite head moderator

Contact info
-----------------------------------------------------
Discord Link For more info. https://discord.gg/55yWGGpjGP
Email: ***@***.***
Phone number: 708-821-7559
Twitch: fablefrostbite
YouTube: Frostbite Channel
Discord: Frostbite Channel#8789

**Comment by SowinskiBraeden** [comment]
Our goal for Lines Police cad is a free open source cad for anybody to use. Mainly targeted towards GTA V roleplay, though used as a cad for Roblox too. It is 100% free, no downloads. It runs in the browser of your desktop or mobile device. Creating civilians and registering cars and firearms are all done within the website, there is no official connection to GTA V, allowing any user, even when playing Roblox, to use our site. We do not build new custom cad's for people and are unable to include a Roblox Map as there is no official Roblox map, and considering our demographic is targeted to GTA V roleplay.
