### ISSUE TITLE
Allow spaces in First and Last Name spot when creating civilians

### ISSUE THREAD

**Issue by NickyScarfo** [Linesmerrill/police-cad#612]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I'd like to have the option to have a space in a civilian's first and/or last name. Some people have 2 parts to their last name or first name. IE: "Juan Pablo" or "Von Richthofen". There's currently no option to have a space in either first name or last name when creating civilians

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Yeah this was originally a requirement to store the data in our database. I think we can probably allow spaces in the first and last name now. Let me do some research and ill update this ticket with my findings. Thanks for creating this.
