### ISSUE TITLE
Option for random name / plate results. Custom citations / offenses.

### ISSUE THREAD

**Issue by Tipsyquickscope** [Linesmerrill/police-cad#615]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- 
We love the work you do, and appreciate that a program such as this is free. Thank you for what you do. 
Random search results is pretty self explanatory. 
For custom citations, I was looking for custom offenses, specifically the option to input custom offenses such as "Failure to display license plate or failure to wear helmet." 
Once again, love the work you do!

**Comment by Linesmerrill** [comment]
We do support custom citations.

Scroll to the bottom when selecting the Fines and select 'Other':
![Screen Shot 2022-03-26 at 4 28 52 PM](https://user-images.githubusercontent.com/15384983/160260461-3a5bb158-ce22-4bc1-94ad-a74724d65444.png)



You can then enter the fine name:
![Screen Shot 2022-03-26 at 4 29 38 PM](https://user-images.githubusercontent.com/15384983/160260462-5399f822-f5ba-4fa7-85c7-0fba666980fe.png)

**Comment by Tipsyquickscope** [comment]
Awesome, thank you. Apologies for not experimenting further and seeing it
for myself. I do appreciate you reaching out as well. Take care.

**Comment by Linesmerrill** [comment]
No worries 😆  Glad I could give you a working solution 👍
