### ISSUE TITLE
Cant see any tickets that were issued to a person.

### ISSUE THREAD

**Issue by casper1270** [Linesmerrill/police-cad#616]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- tickets are not appearing at the bottom under citations.

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]
![image](https://user-images.githubusercontent.com/102204925/159626925-062139ba-b654-41c7-83e9-5281de2c6262.png)

- others are able to see citations for this person and I am unable to.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]  Using cad on chrome, have tried on other browsers and seems to be a common issue

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Thanks for creating a bug for this. Was this the first name shown in the results or not?

**Comment by Linesmerrill** [comment]
We've seen where it will show citiations for the first name and not any others if there are multiple results returned when searching a name

**Comment by Linesmerrill** [comment]
Fixed here: https://github.com/Linesmerrill/police-cad/releases/tag/v2.34.0
