### ISSUE TITLE
Supervisor panel

### ISSUE THREAD

**Issue by Myguy15** [Linesmerrill/police-cad#626]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I would like a supervisor panel
- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

- see all units and see who dispatch is
-

**Comment by Linesmerrill** [comment]
This is a good suggestion!
