### ISSUE TITLE
Remove/Reinstate Gun permits

### ISSUE THREAD

**Issue by LTCPhantom** [Linesmerrill/police-cad#635]
Hello, I have a suggestion, can we make it to where police, and dispatch can remove gun permits/instate them? also can we add the 
option to make perms...for example, make it to to where a community owner can make someone an officer, or dispatch, so not just everyone, can access dispatch, police, or even fire/ems. I would like a  more "secure" system. The C.A.D, however is doing well for 
the project it is, and Is very good at what it was made to do.

**Comment by Linesmerrill** [comment]
Great suggestions! Yeah let me update this ticket to reflect the ask to remove/reinstante gun permits 👍 

We already have a ticket tracking the permissions work, so that should be completed as soon as we get it fully tested.
