### ISSUE TITLE
Create cases that can be assigned to Officers

### ISSUE THREAD

**Issue by RAGNREAGAN84** [Linesmerrill/police-cad#636]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- hi i was hoping that you could create a section on the tool bar for cases that can be used for suspect names and info and well as notes and things of that nature and make it where dispatch will assign the case to a certain officer because i love using your guys CAD but i mostly play as a detective and better tools that are featured on said website would be great 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Great suggestion! Can you give us some examples of what a case would look like?

**Comment by RAGNREAGAN84** [comment]
I don’t have any picture examples because all of mine are on paper but I
know when you make an arrest it gives you a number so what I was thinking
is have a section like police or dispatch were you can see what are open
and add P.O.I (people if intrest) evidence type things, eye witness
statements etc
