### ISSUE TITLE
gas 

### ISSUE THREAD

**Issue by BentleyZaun** [Linesmerrill/police-cad#639]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Can you add a bit more detail around what you would like to see added for this? Putting 'gas' is not descriptive nor helpful for our developers to understand what you would like to see added/addressed. Thanks

**Comment by BentleyZaun** [comment]
Sorry i would like the gas mod so us civs can fill up our cars with gas.
