### ISSUE TITLE
Civilian Photos

### ISSUE THREAD

**Issue by Markus-2022** [Linesmerrill/police-cad#645]
I suggest a new option on "Add Civilian" panel. I suggest an option who _can_ you add a photo of this new civilian. Like Sonoran CAD.

Thanks for read this. 

_Markus._

**Comment by Linesmerrill** [comment]
Thanks for the suggestion! We went back and forth on this and we didn't have enough people interested in adding this so it kept getting pushed out further on our schedule. If we end up getting more requests for this then we can hopefully prioritize it. Thanks!
