### ISSUE TITLE
Impound button

### ISSUE THREAD

**Issue by dawolfqueen** [Linesmerrill/police-cad#655]
I think it would be an amazing feature to have an impound button.

Law enforcement like the police side or at least Dispatch Operations has an option to mark a vehicle as impounded in the system when looking up it's license plate. This feature would be as like similar to the feature where you mark a vehicle as stolen, and it would show up as a red flag similar to how it would a stolen vehicle when looked up.

**Comment by Linesmerrill** [comment]
Yeah that's sounds straightforward enough to me. I'll take a look 👍

**Comment by dawolfqueen** [comment]
Thanks! I think it would be a good addition to the CAD. It would also help
officers find vehicles stolen from impound. Thanks again for looking into
this!
