### ISSUE TITLE
Issue finding civilians by name as Police and Dispatch

### ISSUE THREAD

**Issue by Jr8899fan** [Linesmerrill/police-cad#657]
**Describe the bug**
[_A clear and concise description of what the bug is._]
When members of the community creat a civillian j cannot look them up in the police or dispatch cad as it says not found but they have the civillian created 
- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Just want to verify some details.

1. Are you in a community or not? [Yes/No]
2. Were the civilians created in that community? [Yes/No]
3. Does this seem to be happening for all civilians or only for some?

Let's start with those questions, then we can debug further. 👍
