### ISSUE TITLE
Authorization of certain sections to users

### ISSUE THREAD

**Issue by VincentRPS** [Linesmerrill/police-cad#662]
**Describe the solution you'd like**

- Civ Section (Authorized)
- Police Section (Unauthorized)

**Implementation Details**

I want a system where you can pick what sections a user can go through, rather then having them open to all sections.
This could be possibly done by having a different invite code for every section which the user joins through or another system which involves the admins, like manual verification and authorization.

**Comment by Linesmerrill** [comment]
We can track this here: https://github.com/Linesmerrill/police-cad/issues/563
