### ISSUE TITLE
The shortcut to the website does not work at all

### ISSUE THREAD

**Issue by reidar2002** [Linesmerrill/police-cad#678]
**Describe the bug**
The shortcut to the website is not working at all 

- 

**To Reproduce**
Try to write cad, Cad, CAD, .cad,/cad,.Cad or any other type of way to activate the shortcut

**Expected behavior**

Get a link to the website and the code for the community 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- how can I take a screenshot something that isn’t there?

**Desktop (please complete the following information):**
 - all types of ways to use discord 
 

**Smartphone (please complete the following information):**
All from iPhone 5-14 and different types of android 

**Additional context**
[_Add any other context about the problem here._]

- please help!

**Comment by Linesmerrill** [comment]
Thanks for contacting us. Can you give us an example of the link that you are having issues with?

**Comment by SowinskiBraeden** [comment]
This issue has been resolved via Discord, there was no bug with the bot. A simple mistake was made. Though after request from @reidar2002 this feature has now been added to the bot which can be viewed in the [latest commit](https://github.com/SowinskiBraeden/police-cad-bot/commit/3ce08793c969014f3d2992efb5fdb3399ee201a2)
