### ISSUE TITLE
Partnering with Roblox ER:LC game.

### ISSUE THREAD

**Issue by Piefesday** [Linesmerrill/police-cad#692]
I would like you to partner with ER:LC Roblox (ER:LC= Emergency Response : Liberty County

ER:LC has already partnered with Sonoran Cad if you know.

Please let the developers know if you would like to partner.
Discord server: https://discord.gg/prc 
Game: https://www.roblox.com/games/2534724415/Emergency-Response-Liberty-County
PS: Contact Mr Fergie on discord for any partnership: <img width="365" alt="Screen Shot 2023-01-09 at 23 08 09" src="https://user-images.githubusercontent.com/122285611/211327001-6bb05e09-6869-48bb-99df-db5ab7330169.png">
2nd PS: Please ask the moderators FIRST for a partnership. Or one of the devs.

**Comment by Linesmerrill** [comment]
Thank you for the additional information here. We will look into this and see what we can do. 👍🏻
