### ISSUE TITLE
The ability for officers too be able too click on each arrest report  they have made and be able to view the all the details for their referencing same with citations

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#696]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- The ability for officers too be able too click on each arrest report  they have made and be able to view the all the details for their referencing same with citations

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by ArtJohn1** [comment]
That would be awesome I just had a huge arrest and I can't view **everything.**
