### ISSUE TITLE
add a new feature 

### ISSUE THREAD

**Issue by SSRPPBRP2023** [Linesmerrill/police-cad#703]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]
i would like a bit wher emy officers can add a badge number to there name so it easier and where it shows it on the dispatch page aswell 
- 

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
You can add a call sign by logging in, navigating to settings and setting a call sign. This will then be shown up both on your account as well as the dispatch page.

If there is something else you would like to see let us know.
