### ISSUE TITLE
Fire

### ISSUE THREAD

**Issue by Bendjdjdjdjdj** [Linesmerrill/police-cad#709]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by Linesmerrill** [comment]
Hello, can you please add some context and then reopen when you have a valid request. Thank you
