### ISSUE TITLE
Application for phones

### ISSUE THREAD

**Issue by AlphaJason55** [Linesmerrill/police-cad#710]
**Describe the solution you'd like**
[_A clear and concise description of what you want to happen._]

- I would like for lines cad to be made into an application for phones both apple and Android other than running through chrome

**Implementation Details**
[_Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)_]

-

**Comment by Linesmerrill** [comment]
Thanks for sharing your suggestion. We are actively working on a mobile app right now actually. We are in the very early testing phase. Stay tuned to our socials and discord for more updates in the future. Thank you!
