### ISSUE TITLE
Dispatch is broken

### ISSUE THREAD

**Issue by blueninjaViper** [Linesmerrill/police-cad#715]
There seems to be an issue with the Dispatch feature as it is currently not functioning properly. Users are unable to create, call or delete any active calls due to its buggy behavior. Additionally, once in the Dispatch tab, it is impossible to exit without exiting the entire app.

**Comment by Linesmerrill** [comment]
Thank you for bringing this to our attention. Do you have an example of something that is not working correctly? Our first step is to try and recreate the issue on our side so we can correctly diagnose and fix it.

- Do you have any steps we can follow to see the issue?
- Are you on Mobile or Desktop? (do you tend to see the issue on a certain platform?)

> it is impossible to exit without exiting the entire app

Do you mean to say if you want to change from Dispatch to Civilian, you have to go back to the home page and then click on Civilian?
