### ISSUE TITLE
can not see my  License plates or guns

### ISSUE THREAD

**Issue by dsmcshark** [Linesmerrill/police-cad#733]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- can not see gun or my car 

**To Reproduce**
[_Steps to reproduce the behavior:_]

**Expected behavior**
[_A clear and concise description of what you expected to happen._]

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[_Add any other context about the problem here._]

-

**Comment by dsmcshark** [comment]
Can that seem unlicensed plates or my gun's

**Comment by Linesmerrill** [comment]
Are you in a community or not? Also are you not able to see them as a civilian or when searching as police/dispatch?

**Comment by dsmcshark** [comment]
yes

**Comment by dsmcshark** [comment]
i can not see them in civilian

**Comment by Linesmerrill** [comment]
Ok taking a look. Can you see them after refreshing?

**Comment by dsmcshark** [comment]
i did refresh but still not seeing them

**Comment by Linesmerrill** [comment]
Can you try creating a new civ and select "auto" for creating a civ?

**Comment by dsmcshark** [comment]
ok did it

**Comment by Linesmerrill** [comment]
Ok does that now show up for you? If so, can you create a license for that civ?

**Comment by dsmcshark** [comment]
yes

**Comment by Linesmerrill** [comment]
Ok can you still see the civ and the license?

**Comment by dsmcshark** [comment]
yes

**Comment by Linesmerrill** [comment]
Ok great!

**Comment by dsmcshark** [comment]
think you
