### ISSUE TITLE
Civilian Profile Image bug

### ISSUE THREAD

**Issue by Markus-2022** [Linesmerrill/police-cad#754]
**Describe the bug**
[_A clear and concise description of what the bug is._]

- 

**To Reproduce**
[_Steps to reproduce the behavior:_]
1. Go to civilian Profile 
2. Click on 'image icon'
3. Can't

**Expected behavior**
I expected to put a photo from my files on Image icon in my civilian profile.

- 

**Screenshots**
[_If applicable, add screenshots to help explain your problem._]

- 

**Desktop (please complete the following information):**
 
 - Browser [OperaGX]
 

**Smartphone (please complete the following information):**
 - Device: [Redmi 12]
 - Browser [Chrome ]

**Comment by Markus-2022** [comment]
![IMG_20240405_221405](https://github.com/Linesmerrill/police-cad/assets/105107020/818f318b-4005-4e98-92b7-8c44fa65d2c5)

**Comment by Linesmerrill** [comment]
This feature is coming soon. Not currently implemented.
