### ISSUE TITLE
Account Randomly Gone/Unable To Login

### ISSUE THREAD

**Issue by TheAlphaWolf2005** [Linesmerrill/police-cad#755]
So I was roleplay with a few of my buddies on GTA 5, and we frequently used LinesCAD for our roleplaying world. I was switching over from cop to civilian, got logged out, and now i can't even log back in, it also wont even send my gmail a password reset, which I've tried to get multiple times. If there is anyway to help, please helo me get my account back.

**Comment by Linesmerrill** [comment]
Hello, can you contact our support team? They will look into the issue and follow up with any specific details. Send them an email here: support@linespolice-cad.com
