### ISSUE TITLE
Add Pilot license

### ISSUE THREAD

**Issue by Linesmerrill** [Linesmerrill/police-cad#77]
**Describe the solution you'd like**
Add a pilot license for civilians.

**Implementation Details**
This could be pretty simple. Just a basic toggle to show that the civilian has a pilots license. 

**Possible Side Effects**
None

**Comment by Linesmerrill** [comment]
Request for this again, so reopening

**Comment by Linesmerrill** [comment]
Can be combined with: https://github.com/Linesmerrill/police-cad/issues/457

**Comment by DixieKing** [comment]
Can you by chance add a way to vocally dispatch someone
