### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by Cody6887** [Linesmerrill/police-cad#90]
**Describe the solution you'd like**
Add a phone into the CAD/MDT and job like uber, lawer, taxi, 911, twotter, Pegasus, tow service, ETC
*Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)
Adding a jobs tab to the CAD/MDT where people can access the CAD/MDT for those jobs
**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?
More people would be interested and it would add a whole new story to peoples RP groups which would help them grow

**Comment by Linesmerrill** [comment]
What we have completed for this is the ability to enter a job profession when creating a civilian in the website. It is a text input field so you can enter whatever job you want. This can later be updated by clicking on that civilian and modifying the field.
