### ISSUE TITLE
Put ems and fire 10 codes in

### ISSUE THREAD

**Issue by gavingavinbus** [Linesmerrill/police-cad#91]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Hey I think this is a great suggestion! We could add the fire/EMS codes to the fire/EMS dashboard. Awesome idea. Reopening this for our team to take a look.

**Comment by Linesmerrill** [comment]
The work for this can be found here: https://github.com/Linesmerrill/police-cad/pull/97

**Comment by Linesmerrill** [comment]
Completed here: https://github.com/Linesmerrill/police-cad/pull/97
