### ISSUE TITLE
id like for there to be a option for registering company vehicles so its better and easier for cops to run compan vehicle plates

### ISSUE THREAD

**Issue by trooper2354** [Linesmerrill/police-cad#93]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Great suggestion! This is something that you can already do when creating a new vehicle. 

To register a vehicle as a 'Company Vehicle' simply follow these steps:

1. Log In as a Civilian
1. Click on Add New Vehicle
1. Enter the vehicle details, but for Registered Owner list the Business that would own the vehicle

Example of creating a company vehicle:

![image](https://user-images.githubusercontent.com/15384983/72666406-22052f00-39cf-11ea-9a32-ec03697da320.png)

It will show up under your list of Vehicles, but when the police run that plate they will see that it is registered to the company you listed.

Example of the search from the police dashboard:

![image](https://user-images.githubusercontent.com/15384983/72666427-6690ca80-39cf-11ea-890f-d94f27ce8176.png)


This should solve the issue you reported, as such I am going to close this. If you have any other comments directed related to this feature - feel free to post directly on this ticket. Thank you!
