### ISSUE TITLE
Arrest reports and Civilians seeing their records.

### ISSUE THREAD

**Issue by FloppyCat99** [Linesmerrill/police-cad#94]
**Arrest Report**
Currently its not possible to write an arrest report and have a prior arrest be on someones name, I think this would a great addition.

**Seeing your record as a civilian**
Currently, you can't see prior that a character has which makes it difficult to choose a character as, you don't know what priors they have on them, so if you could see the record of your civilians record as a Civilian. It be great addition too.

**Comment by Linesmerrill** [comment]
Fantastic suggestions @FloppyCat99 ! Thanks for submitting these.

- We are actively working on testing the arrest reports here: https://github.com/Linesmerrill/police-cad/pull/102

- And we will put the request to see the citations, warnings and arrest reports under the civilian profile into our backlog. 👍

**Comment by Linesmerrill** [comment]
Arrest report completed here: https://github.com/Linesmerrill/police-cad/pull/102

**Comment by Linesmerrill** [comment]
I split out the civilians and records here: https://github.com/Linesmerrill/police-cad/issues/115
