### ISSUE TITLE
I would like you guys to add a dispatch section

### ISSUE THREAD

**Issue by keedanthegodgamer** [Linesmerrill/police-cad#95]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Hi @keedanthegodgamer! Thanks for suggesting this. We already have work related to this being worked on over here: https://github.com/Linesmerrill/police-cad/issues/30. As such I am going to close this ticket as a duplicate. Feel free to follow along at the linked issue.
