### ISSUE TITLE
Skin color

### ISSUE THREAD

**Issue by tuiio** [Linesmerrill/police-cad#98]
**Describe the solution you'd like**

**Implementation Details**
Add any and all specific things you would like to see implemented. These can include things such as limiting the input for a input box to only include specific characters. (This can be as technical as you would like to make it, including code examples)

**Possible Side Effects**
What are some of the adverse reactions that adding this could bring to the website?

**Comment by Linesmerrill** [comment]
Adds additional information to civilians.

**Comment by Linesmerrill** [comment]
Great suggestion @tuiio ! Thanks for adding this to our list. We will try and prioritize this for you. 👍

**Comment by Linesmerrill** [comment]
This is a duplicate, here is the original: https://github.com/Linesmerrill/police-cad/issues/72
